README.md
I've also included a clarification regarding type intersections using & in Scala 3.
=> update documentation to refer to `>` as "pending"

kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/main/scala/kyo/layers.scala, kyo-core/shared/src/main/scala/kyo/options.scala, kyo-core/shared/src/main/scala/kyo/tries.scala, kyo-core/shared/src/test/scala/kyoTest/layersTest.scala
Introduces new type `Layer[Sin, Sout]`, representing a handler of `Sout` that requires further handling of `Sin` and that cannot transform the output of the handled effect. The latter restriction allows for commutative composition, so that layers can be combined in any order without affecting (as far as I can tell) the resulting effect.
`Layer` provides a mechanism for dependency injection, by allowing you to compose `Envs` handlers. It should be possible to add a function similar to ZIO's `.provide`, which automatically wires layers together to satisfy all dependencies.
However, `Layer` can be used more broadly as a means to simplify certain kinds of effect handling. For instance, it can be used to between different kinds of failures.
=> Add Layer trait and Layer factory methods on Envs, Aborts, Tries, and Options

kyo-core/shared/src/main/scala/kyo/vars.scala, kyo-core/shared/src/test/scala/kyoTest/varsTest.scala
As @ghostdogpr described in https://github.com/getkyo/kyo/issues/195, Kyo doesn't have an effect equivalent to `State` yet. The [Sums](https://github.com/getkyo/kyo/blob/c1ef74632d171bc619db1b37da7c8c4f251ef8b9/kyo-core/shared/src/main/scala/kyo/sums.scala#L8) effect provides similar functionality but I decided not to document it because I'm not happy with its design since it bundles both `State` and `Writer` in the same effect.
Introduce the new `Vars` effect.
- I think the name is more intuitive than `State` for newcomers but I'm open to suggestions.
- This effect is similar to other effects like `Envs` but I decided to try a new encoding to avoid having multiple `Vars` in the pending effect set. For example, if a computation uses `String` and `Int` vars, it can be declared as `T < …
=> Vars effect

kyo-core/shared/src/main/scala/kyo/internal/FlatImplicits.scala
I've been exploring the codebase to try to get a grasp on some of the magic (simultaneously scouring the _Do Be Do Be Do_ paper and attempting to build a toy replica) 🤩 It's such a cool library, @fwbrasil! 
Back in the day, I was a huge fan of Haskell's [Polysemy](https://github.com/polysemy-research/polysemy#readme)—an extensible effects library with some really great ergonomics. When I switched to Scala, I sought out something similar. And after flailing about the Cats ecosystem for a time (trying and failing to enjoy `Eff`), I finally gave ZIO a try. Of course, ZIO has a completely different implementation, but it provided an even better experience than Polysemy, whereas I'd found the Cats ecosystem to be significantly more verbose than Haskell (all those required type annotations 😭). …
=> Update `>` to `<` in `Flat` implicit error

build.sbt, kyo-bench/src/main/scala/kyo/bench/MtlBench.scala
See https://github.com/getkyo/kyo/issues/195 (originally from https://github.com/ghostdogpr/mtl-benchmarks)
```
[info] Benchmark            Mode  Cnt     Score     Error  Units
[info] MtlBench.syncKyo    thrpt    5  2822.207 ±  66.487  ops/s
[info] MtlBench.syncRWST   thrpt    5  2574.217 ± 155.879  ops/s
[info] MtlBench.syncZPure  thrpt    5  9352.017 ± 303.491  ops/s
```
=> Add ZPure and RWST to mtl benchmarks

build.sbt, kyo-bench/src/main/scala/kyo/bench/StreamBench.scala, kyo-core/shared/src/main/scala/kyo/channels.scala, kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/test/scala/kyoTest/channelsTest.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala
An initial implementation of the `Streams` effect with an encoding inspired by Unison's `Stream` [ability](https://exercism.org/tracks/unison/exercises/stream-ops). With this encoding, computations can emit multiple streams. For example: `Int < (Stream[Int] & Stream[String])` is a computation that will emit two streams and return an `Int`.
Although the encoding is elegant, I'm not sure about usability. Performing more complex operations on elements of the pending effect set is something other effects don't do and users might have trouble to understand the approach:
```scala
// Note how 'emit' returns a computation that
// produces 'Unit' and has the 'Streams[Int]' 
// pending effect indicating that it also produces 
// a stream of 'Int' values.
val a: Unit < Streams[Int] = …
```
=> unison-inspired streams

kyo-bench/src/main/scala/kyo/bench/StreamBufferBench.scala, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala, kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala
The `Streams` effect introduced by https://github.com/getkyo/kyo/pull/235 has an inconvenient API that doesn't allow users to chain stream transformations and operates at a high level of abstraction by transforming `Streams` in the pending effect set. This PR aims to restructure the API to provide better usability. The main idea is providing a `Stream` opaque type that makes it more convenient to use `Streams`:
```scala
// A Stream produces a final value 'T', 
// emits stream elements 'V' and can 
// have other pending effects 'S'.
opaque type Stream[+T, V, -S] = 
T < (Streams[V] & S)
// The 'initSource' method takes a regular
// computation and transforms it into a
// 'Stream'.
def a(v: Int < (Streams[String] & IOs)): Stream[Int, String, IOs] =
Streams.initSource[String](v)
// It's …
```
=> streams: usability improvements

kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/hubs.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/options.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/retries.scala, kyo-core/shared/src/main/scala/kyo/seqs.scala, kyo-core/shared/src/main/scala/kyo/sums.scala, kyo-core/shared/src/main/scala/kyo/vars.scala, kyo-direct/src/main/scala/kyo/TestSupport.scala
Scala has a behavior that when there's a method with a restricted set of effects, it automatically lifts the parameter into a nested computation in case the pending set of the provided parameter doesn't match:
```scala
def test1[T](v: T < IOs) = ...
def test2(v: Int < Fibers): Int < Fibers < IOs =
test1(v)
```
The `Flat` check is able to detect this issue and produce a better error message.
```scala
def test1[T](v: T < IOs)(using Flat[T < IOs]) = ...
def test2(v: Int < Fibers) =
test1(v) // compilation failure with details of the effect mismatch
```
Several methods use an implicit `Flat` with the full expected type for this reason but we don't need the full type in case the pending set isn't restricted since Scala won't attempt to do the automatic lifting. We can define the implicit …
=> simplify Flat usage

kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/main/scala/kyo/tags.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala
Kyo uses a custom tag mechanism based on Izumi that is designed to avoid allocations. The macro generates a string at compile time that becomes a constant in the class pool, so tags can be obtained and compared for equality without any runtime allocations.
That's the reason the error message in #244 is so cryptic. I've fixed the error messages to parse the `Tag` string into a regular Izumi tag to provide a better string representation. With this change, the error message in #244 becomes:
```
[info] - union tags *** FAILED *** (8 milliseconds)
[info]   kyo.package$KyoBugException: Unhandled effect: Aborts[-{String | Boolean}]. Please file a ticket.
[info]   at kyo.package$KyoBugException$.apply(package.scala:61)
[info]   at kyo.package$.bug(package.scala:66)
[info]   at …
```
=> Improve error messages in case of bugs + reproduce #244

kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala
Kyo currently only checks effect tags for equality, which isn't enough for effects like `Aborts`. See https://github.com/getkyo/kyo/issues/244 for more background.
This PR introduces a new method to `Handler` called `accepts`, which can be overriden with custom tag matching logic. I've added the override to `Aborts` to consider sub-typing for it and it seems to fix the issue.
I noticed another issue with the API not enabling handling of a super class and added a pending test for it. I think we'd need to add variance to `HasAborts` to fix it.
=> aborts: improve support for union types (fixes #244)

README.md, kyo-core/shared/src/main/scala/kyo/loops.scala, kyo-core/shared/src/test/scala/kyoTest/loopsTest.scala
Kyo's execution model evaluates pure code strictly as [described in the readme](https://github.com/getkyo/kyo/blob/457d9f5958afb6af8b847245164d85de3362e439/README.md?plain=1#L1741), which makes recursive computations without effect suspensions not stack safe by default. The current recommendation is introducing an effect suspension like `IOs` to achieve stack safety.
Although introducing an effect suspension can be convenient in some cases, it can become problematic in code that doesn't have a reasonable way to introduce suspensions. For example, I've been working on the `Streams` effect and adding `IOs` to its execution just to ensure stack safety doesn't seem reasonable. I could emit an empty chunk but that would introduce unnecessary overhead and doesn't feel like a proper solution. …
=> Loops: Stack-Safe Recursion

README.md, kyo-bench/src/main/scala/kyo/bench/MtlBench.scala, kyo-core/shared/src/main/scala/kyo/chunks.scala, kyo-core/shared/src/main/scala/kyo/loops.scala, kyo-core/shared/src/main/scala/kyo/sums.scala, kyo-core/shared/src/test/scala/kyoTest/chunksTest.scala, kyo-core/shared/src/test/scala/kyoTest/sumsTest.scala, kyo-tapir/src/main/scala/kyo/routes.scala
Kyo provides stronger guarantees regarding the purity of its effects than other effect systems typically do. A common pattern in libraries like ZIO is to [leverage mutable iterators internally](https://github.com/zio/zio/blob/62173a1aad4be0a369a16cb234f43db5c896337b/core/shared/src/main/scala/zio/ZIO.scala#L3333-L3341) to process sequences:
```scala
def foreach[R, E, A, B, Collection[+Element] <: Iterable[Element]](in: Collection[A])(
f: A => ZIO[R, E, B]
)(implicit bf: BuildFrom[Collection[A], B, Collection[B]], trace: Trace): ZIO[R, E, Collection[B]] =
ZIO.suspendSucceed {
val iterator = in.iterator
val builder  = bf.newBuilder(in)
ZIO.whileLoop(iterator.hasNext)(f(iterator.next()))(builder += _).as(builder.result())
}
```
This form of local mutability doesn't seem ideal but it's …
=> introduce chunks

kyo-core/jvm/src/main/scala/kyo/scheduler/Scheduler.scala
@hearnadam I was finally able to reproduce using another machine. The issue actually isn't related to the preemption flag directly but with the scheduler not even sending the preemption signal. Could you check again in your machine?
Kyo's scheduler uses a dynamic policy for the number of threads that can reduce the worker count (maxConcurrency) but it's possible an existing worker with index greater than `maxConcurrency` is still running. This PR changes the scheduler to cycle all allocated workers, regardless if they're accepting workload.
The scheduler's code isn't very testable so I don't see an easy way to introduce a test for the bug. I'll follow up with a separate PR moving the scheduler to a new module and refactoring the code to introduce tests.
=> ensure the preemption signal is dispatched to all workers

kyo-bench/src/main/scala/kyo/bench/FailureBench.scala, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala
This new benchmark is designed to reproduce https://github.com/getkyo/kyo/issues/275. Current results on my M2:
```
[info] Benchmark               Mode  Cnt        Score       Error  Units
[info] FailureBench.forkCats  thrpt    5   132505.248 ± 12212.895  ops/s
[info] FailureBench.forkKyo   thrpt    5    28640.191 ±  1648.773  ops/s
[info] FailureBench.forkZio   thrpt    5    92255.834 ± 11252.393  ops/s
[info] FailureBench.syncCats  thrpt    5   133276.418 ±  4492.660  ops/s
[info] FailureBench.syncKyo   thrpt    5    43961.788 ±  2972.598  ops/s
[info] FailureBench.syncZio   thrpt    5  1453020.306 ± 54500.737  ops/s
```
Kyo's profiling sessions are dominated by Izumi's parsing and subtype checking:
Allocations
CPU
=> introduce failure benchmark

kyo-bench/src/main/scala/kyo/bench/RandomBench.scala, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala
```kyo/clean;jmh:clean;jmh:run -wi 10 -i 5 -r 1 -w 1 -t 1 -rf json -foe true -prof gc RandomsBench```
```
[info] Benchmark                                  Mode  Cnt        Score      Error   Units
[info] RandomsBench.forkCats                     thrpt    5      523.631 ±    6.182   ops/s
[info] RandomsBench.forkCats:gc.alloc.rate       thrpt    5     4075.822 ±   47.943  MB/sec
[info] RandomsBench.forkCats:gc.alloc.rate.norm  thrpt    5  8163050.052 ±   40.221    B/op
[info] RandomsBench.forkCats:gc.count            thrpt    5       78.000             counts
[info] RandomsBench.forkCats:gc.time             thrpt    5       47.000                 ms
[info] RandomsBench.forkKyo                      thrpt    5      656.814 ±  340.748   ops/s
[info] RandomsBench.forkKyo:gc.alloc.rate …
```
=> Introduce Randoms bench

kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala
Begin addressing https://github.com/getkyo/kyo/issues/266
Later, these services will enable us to build a test integration on `KyoApp` instances. Using KyoApp should enable users to run tests as `Main`s.
This will also simplify providing a custom logger.
=> Enable providing custom services in KyoApp

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/package.scala
continuation of https://github.com/getkyo/kyo/pull/278#discussion_r1579100968
I think logging the exception itself should be more helpful, with better interop, etc.
But if there's a good reason to print it manually then no worries, feel free to close the PR.
=> Log the exception in logger

kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala
- pass failure value for `Aborts.when` by name, potentially avoiding allocations
- add unit test for `Aborts.when`
I intentionally did not create an API for `run`/`catching` as it's unergonomic with type unions. I think followup work can be done there depending on how https://github.com/getkyo/kyo/issues/275 is resolved.
This massively improves the ux of Aborts in my opinion.
=> add type inferred Aborts API

kyo-test/shared/src/main/scala/kyo/test/KyoSpecDefault.scala, kyo-test/shared/src/main/scala/kyo/test/interop/zio.scala, kyo-test/shared/src/test/scala/kyo/test/KyoSpecDefaultSpec.scala, kyo-test/shared/src/test/scala/kyo/test/interop/zioSpec.scala
- Ensure interruptions work correctly
- migrate KyoSepcDefault
=> Interop Kyo Fiber & ZIO

README.md, kyo-bench/src/main/scala/kyo/bench/FailureBench.scala, kyo-bench/src/main/scala/kyo/bench/MtlBench.scala, kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/options.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/api/Handler.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-tapir/src/main/scala/kyo/routes.scala, kyo-test/shared/src/test/scala/kyo/test/KyoSpecDefaultSpec.scala
As discussed in #275, this PR changes `Aborts` to rely solely on regular reflection of aborted values instead of type tags. It's an approach similar to ZIO. The [benchmark results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/3964a7ff775d855268b809cfee7fab84/raw/31e8b5b5b1dab3f70ec6aee60ef12873ba68dd1b/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/3964a7ff775d855268b809cfee7fab84/raw/31e8b5b5b1dab3f70ec6aee60ef12873ba68dd1b/jmh-result-candidate.json) confirm the fix of the bottleneck very well 🤣
=> Avoid Tags in Aborts (fixes #275)

kyo-bench/src/main/scala/kyo/bench/ForkJoinBench.scala, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala
Port of ZIO's benchmark: https://github.com/zio/zio/blob/b84b12892e8b6c329e5ace56f4c4ecc2d21ce094/benchmarks/src/main/scala/zio/ForkJoinBenchmark.scala#L1
Results with M2 Max:
https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/ea9fcff9a00b6f79a1799b3342d625d7/raw/5d4876a9257176924c8bd19a63c48da4769b3821/jmh-result.json
=> introduce fork/join benchmark

kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/core.scala
There's no need to check the type at the last case of the match, especially considering that it uses `@unchecked`.
=> core: reduce bytecode size by avoiding type checks

kyo-core/shared/src/main/scala/kyo/loops.scala, kyo-core/shared/src/main/scala/kyo/seqs.scala, kyo-core/shared/src/test/scala/kyoTest/loopsTest.scala, kyo-core/shared/src/test/scala/kyoTest/seqsTest.scala
Moves `repeat` from `Seqs` to `Loops` and introduces a new `forever` method to loop indefinitely.
=> loops: repeat and forever

kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-scheduler/js/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/shared/src/main/scala/kyo/scheduler/Task.scala
This is a bug introduced by https://github.com/getkyo/kyo/pull/278. I noticed it while testing the new scheduler under stress. I'm not sure how to introduce an automated test for this given that it's a performance issue and this code isn't very testable in isolation. I've tried designing a benchmark to measure preemption performance a few times unsuccessfully.
=> fix io task runtime tracking

.github/workflows/build.yml, build.sbt, kyo-zio/shared/src/main/scala/kyo/zios.scala, kyo-zio/shared/src/test/scala/kyo/ziosTest.scala
I've recovered the ZIO integration and identified a way to handle both Kyo and ZIO computations by manually implementing the evaluation loop handling all effects at once, [similarly to `IOTask`](https://github.com/getkyo/kyo/blob/be752ed1e6d8477da28a42d9847fea8867922790/kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala#L27). This approach doesn't require blocking threads and it seems it can handle async boundaries and propagate interrupts/failures correctly.
=> zio integration

build.sbt, kyo-bench/src/main/scala/kyo/bench/HttpClientBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/TestHttpServer.scala, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala
I'm working on the performance of `Requests`. I couldn't find a way to instantiate `zio-http`'s client once and reuse it so I've disabled the benchmark for ZIO by returning a constant. Please ignore ZIO's results for now.
=> http client benchmarks

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala
While optimizing `Requests`, I noticed a thread stack with nested `worker.drain` frames, which doesn't make sense. The issue is that when a worker is draining, it'll try to reschedule tasks but then `Scheduler.schedule` might pick up the worker itself and call `checkAvailability` on it, which can trigger a nested `drain`.
This was an oversight and is something difficult to test in isolation. The new logic also matches `scheduler.steal`.
=> scheduler: don't check the availability of a submitter worker

kyo-sttp/jvm/src/main/scala/sttp/client3/HttpClientKyoBackend.scala
Java's HTTP client switches execution to `ForkJoinPool` by default, which isn't necessary since STTP already shifts the execution to Kyo's scheduler to process the request. This PR makes the client use an "immediate" executor by default, flushing any `CompletionStage` transformations immediately.
https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/63f13c78df90063bf403a584b647ccd7/raw/7116437f81dc06cdb6c06fdc8f8a711614375314/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/63f13c78df90063bf403a584b647ccd7/raw/7116437f81dc06cdb6c06fdc8f8a711614375314/jmh-result-candidate.json
=> requests: avoid switching to ForkJoinPool

kyo-core/shared/src/main/scala/kyo/fibers.scala
I noticed this while optimizing `Requests`. When a large number of fibers is interrupted, sttp obtains the cause of the `Interrupted` exception, which is synchronized in `Throwable`. In this case, the cause is always `null` since it's a cached exception.
```
"kyo-scheduler-worker-33" #101 [56067] daemon prio=5 os_prio=31 cpu=59.03ms elapsed=0.65s tid=0x00000001018d0400 nid=56067 waiting for monitor entry  [0x00000008834d2000]
java.lang.Thread.State: BLOCKED (on object monitor)
at java.lang.Throwable.getCause(java.base@21.0.2/Throwable.java:422)
- waiting to lock <0x00000002814c7760> (a kyo.fibers$package$Fibers$Interrupted$)
at sttp.client3.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:29)
at …
```
=> fix Fibers.Interrupted to avoid lock contention in `Throwable::getCause`

kyo-sttp/jvm/src/test/scala/kyoTest/requestsLiveTest.scala
Reproduces a [scenario from EasyRacer](https://github.com/jamesward/easyracer/blob/a9aa01afefe00ab905af53a27bb2e2f005b0d00d/scala-kyo/src/main/scala/EasyRacerClient.scala#L27). I'm expecting this to fail in CI and pass once https://github.com/getkyo/kyo/pull/330 and https://github.com/getkyo/kyo/pull/331 are merged.
=> requests: race 10k requests test

build.sbt, kyo-bench/src/test/scala/kyo/bench/BenchTest.scala, kyo-bench/src/test/scala/kyo/bench/CatsBenchTest.scala, kyo-bench/src/test/scala/kyo/bench/KyoBenchTest.scala, kyo-bench/src/test/scala/kyo/bench/ZioBenchTest.scala
It's easy to make mistakes in benchmarks that end up initializing targets other than the one being tested. For example, if `Bench.zioRuntime` were a `val` instead of `lazy val`, all benchmarks would run with ZIO's runtime initialized, including its threads. This kind of mistake can introduce significant noise in the benchmarks.
=> benchs: detect runtime leaks

kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/Flat.scala, kyo-core/shared/src/main/scala/kyo/Joins.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/internal/FlatImplicits.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/test/scala/kyoTest/FlatTest.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala, kyo-test/shared/src/main/scala/kyo/test/KyoSpecAbstract.scala, kyo-test/shared/src/main/scala/kyo/test/KyoSpecDefault.scala, kyo-test/shared/src/main/scala/kyo/test/interop/zio.scala
Fixes https://github.com/getkyo/kyo/issues/327.
Kyo's `Flat` check was designed to have a complex derivation mechanism to provide better error messages in case of a mismatch between the effects a method supports vs the pending effects of its parameters. This derivation mechanism is unsound. This PR removes it.
This results in a regression in usability since error messages don't explicitly show where the mismatch is anymore. It seems a reasonable tradeoff that we can address later.
=> flat check fixes

README.md, kyo-core/shared/src/main/scala/kyo/resources.scala, kyo-core/shared/src/test/scala/kyoTest/fibersTest.scala, kyo-core/shared/src/test/scala/kyoTest/resourcesTest.scala
Fixes https://github.com/getkyo/kyo/issues/353.
The `Resources` effect isn't very flexible in what effects it allows in its APIs. This PR reimplements the effect based on `Fibers`, which allows `Fibers` in any of its APIs in addition to `IOs`, and makes the `acquire` parameter of `acquireRelease` support any effect.
=> better support for other effects in Resources

build.sbt, kyo-bench/src/main/scala/kyo/bench/TagsBench.scala, kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/main/scala/kyo/tags.scala, kyo-core/shared/src/test/scala/kyoTest/envsTest.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala, kyo-core/shared/src/test/scala/kyoTest/tagsTest.scala, kyo-tapir/src/main/scala/kyo/routes.scala, kyo-zio/shared/src/main/scala/kyo/zios.scala
Fixes #339.
Kyo uses tags for effect handling. Izumi's performance has been an important limitation, especially to provide sub-type checking it hot paths. This PR introduces a new `Tag` implementation that bundles the type information in a string format amenable to type comparisons without requiring allocations. Since the string is generated at compile-time, it becomes a constant in the class pool and doesn't require allocations.
The only scenario where this new `Tag` can allocate is when one of the type parameters has an implicit tag. For example:
```scala
def test[T: Tag] = Tag[List[T]]
```
In this case, the macro generates a tree that will concatenate the string representing `Tag[T]` into `Tag[List[T]]`. JIT compilers can many times avoid such allocation, though.
This change introduces …
=> (almost) allocationless tags ⚡

build.sbt, kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/choices.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/defers.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/main/scala/kyo/sums.scala, kyo-core/shared/src/main/scala/kyo/vars.scala, kyo-zio/shared/src/main/scala/kyo/zios.scala
I'm working on a follow up of https://github.com/getkyo/kyo/pull/348 to rely on the new `Tag` in `Aborts`. Something that has been challenging when developing effects is dealing with variance and the `Command` defined as type member:
```scala
class Aborts[-V] extends Effect[Aborts[V]]:
type Command[T] = Left[V, ?] // compilation error because V is contravariant
```
This fails to compile because `V` is contravariant and type members are invariant. It's possible to work it around by making `Command` opaque but then it's necessary to provide bridge methods.
This PR changes the encoding of effects to use a type parameter for the command instead of a type member, which solves this encoding issue with variance.
=> move effect command from member type to type parameter

kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/tagsTest.scala
I'm working on reimplementing `Aborts` and `Envs` based on the new `Tag` but there's a performance regression. This PR introduces optimizations to address it:
1. Each type in a segment is now prefixed with its size encoded as `char`, which avoids scans to find the next element.
2. A hash of the type name is also encoded as a `char` after the length, which enables fast mismatches. For example, when checking `scala.Int` against `scala.Double`, the previous implementation would first compare `scala.` to then find out the type doesn't match. Hash conflicts aren't a concern since, in case of match, the entire type string is checked for equality.
3. Introduces a mechanism to compact the representation of common types.
This change introduces a restriction: type names with more than 94 characters …
=> Tag optimizations

kyo-core/shared/src/main/scala/kyo/aborts.scala
As mentioned in https://github.com/getkyo/kyo/pull/360, I've identified an encoding that allows us to declare effects as `opaque` without breaking the direct syntax. It's not ideal but at least unblocks https://github.com/getkyo/kyo/pull/335.
=> workaround to declare effects as opaque

kyo-core/shared/src/main/scala/kyo/internal/FlatImplicits.scala, kyo-core/shared/src/test/scala/kyoTest/FlatTest.scala
A `Flat` instance can now be derived from `Tag` since its new implementation restricts tags to concrete types, which doesn't include Kyo's pending type.
This change introduces automatic derivation so users don't need to provide implicits for both `Flat` and `Tag` for the same type.
=> automatically derive Flat from Tag

kyo-bench/src/main/scala/kyo/bench/HttpClientRaceContentionBench.scala
This benchmark is similar to easyracer's scenario in https://github.com/getkyo/kyo/issues/347.
Please ignore ZIO's results for now since it's disabled. See https://github.com/getkyo/kyo/issues/329 for more context.
https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/8e5f0b82abc1aff56bdea686b3008be4/raw/2975084ca13768ca7321f0401f344116ba07a3d4/jmh-result.json
=> http client race bench

kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Admission.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Concurrency.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Regulator.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/util/Top.scala, kyo-scheduler/shared/src/main/scala/kyo/scheduler/Task.scala
I'm working on https://github.com/getkyo/kyo/issues/347 and need more visibility on the execution of the scheduler to debug. This PR introduces a `top` utility that can be used in two ways:
- **Console**: It's possible to print the information to the console periodically by setting `-Dscheduler.enableTopConsoleMs=<<interval>>`. Disabled by default.
- **JMX**: The functionality is exposed as an mbean and can be accessed the main class `kyo.scheduler.util.Top`. Enabled by default since there shouldn't be a significant performance penalty.
The utility is lightweight and designed to be used in production as well. Demo:
[![asciicast](https://asciinema.org/a/FFZUkfAuMy5cnb16Q0N8KSKBR.svg)](https://asciinema.org/a/FFZUkfAuMy5cnb16Q0N8KSKBR)
=> scheduler: top utility

kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/choices.scala, kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/defers.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/main/scala/kyo/sums.scala, kyo-core/shared/src/main/scala/kyo/vars.scala
Avoids handler allocations in `Streams`. The benchmarks show no improvement but it's because the JIT is able to avoid the handler allocations. I think it's still worth making the change since that might not be the case in production code.
=> cache stream handlers

build.sbt
@johnhungerford can you try the snapshot and see if `zikyo` correctly builds?
=> scala-js: add java-time dependency

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/util/Top.scala
1. Prints inactive workers separately
2. Shows thread stats for the underlying thread pool
3. Cosmetic improvements
=> scheduler top improvements

kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala
This is the main cause of the regression in https://github.com/getkyo/kyo/issues/347. The `eval` method introduces much more overhead than the previous dedicated loop. The issue is that function applications don't get inlined and producing a thunk to provide to `resume` introduces more indirection, preventing JIT optimizations.
I'll post benchmark results tomorrow.
=> avoid `core.eval` for error handling

kyo-sttp/jvm/src/main/scala/sttp/client3/HttpClientKyoBackend.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-tapir/src/main/scala/kyo/server/NettyKyoServer.scala, kyo-tapir/src/main/scala/kyo/server/NettyKyoServerInterpreter.scala, kyo-tapir/src/main/scala/kyo/server/internal/NettyKyoRequestBody.scala
Scala 3 automatically uses a `lazy val` in the desugaring of `given` statements. This isn't a major optimization but it avoids the `lazy val` by using `inline`.
=> avoid `lazy val` to access `KyoSttpMonad`

kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-sttp/shared/src/test/scala/kyoTest/internal/KyoSttpMonadTest.scala
`KyoSttpMonad` currently spins `ensure` thunks in a background fiber, which doesn't provide backpressure. This PR uses a pattern similar to https://github.com/getkyo/kyo/pull/355 via a `Promise` to address the issue. I've also added a test for the class since it was missing.
=> kyo-sttp: ensure backpressure

kyo-sttp/shared/src/main/scala/kyo/requests.scala, kyo-sttp/shared/src/test/scala/kyoTest/requestsTest.scala
Provides an API to limit the use of the backend with a `Meter`. I need this feature because Kyo is overloading the test http server in benchmarks with the latest optimizations.
=> kyo-sttp: backend meter

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/WorkerTest.scala
Kyo's concurrency regulator can reduce concurrency and make workers inactive. Inactive workers are automatically drained in multiple code paths and don't receive new workload but, if a worker has a long-running task, it can continue running until it finishes. This change makes workers exit as soon as possible.
=> scheduler: ensure workers stop when inactivated

build.sbt, kyo-bench/src/main/scala/kyo/bench/HttpClientBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientRaceContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/TestHttpServer.scala
The Java server became a bottleneck in the http contention benchmarks. This PR migrates it to Vert.x since it's highly optimized. We can't use `kyo-tapir` since it'd be difficult to distinguish between performance changes in the client vs server.
=> kyo-benchs: migrate TestHttpServer to Vert.x

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Queue.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/WorkerTest.scala
I'm working on tracking down the regression in ZIO's benchmarks when I enable the option use Kyo's scheduler and noticed a couple of minor optimization opportunities. There isn't a significant change in benchmark results but I think it's worth it since things can change over time.
=> scheduler: minor optimizations

.github/workflows/build.yml, .scalafmt.conf, build.sbt, kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-scheduler-zio/jvm/src/main/scala/kyo/KyoSchedulerRuntime.scala, kyo-scheduler-zio/jvm/src/test/scala/kyo/KyoSchedulerRuntimeTest.scala
Provides a module integrating Kyo's scheduler as an alternative for `ZScheduler` in ZIO applications.
=> kyo-scheduler-zio

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/util/Top.scala
Untested, but should resolve #396
=> Use `Top.print` to output `Scheduler.Status` to console

kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientRaceContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/ZIORuntime.scala, kyo-scheduler-zio/jvm/src/main/scala/kyo/KyoSchedulerZioRuntime.scala
This is the only way I can think of to initialize a zio-http client once... the zlayer -> runtime mechanism is not type safe, but I don't expect it to be widely used.
Hopefully I fixed the resource leak I had in #354 
/resolves #329 
/claim #329
=> zio-http bench

kyo-bench/src/main/scala/kyo/bench/BlockingBench.scala, kyo-bench/src/main/scala/kyo/bench/BlockingContentionBench.scala
I'm testing the scheduler's scalability and noticed an issue with how it handles blocking. The main issue is the `schedule` method draining blocked workers over and over.
I'm adding these benchmarks to guide the optimization. Current results:
https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/5d0d73efeb75e2ed6f5edb0b5a47bdac/raw/c8773ddbecc1c66f378af2852e326968d604e2dd/jmh-result.json
=> blocking benchmarks

build.sbt, kyo-core/js/src/test/scala/kyoTest/Platform.scala, kyo-scheduler/js/src/main/scala/kyo/scheduler/Scheduler.scala
/claims #302
/resolves #302 
re: your comment @fwbrasil 
- https://github.com/getkyo/kyo/issues/302#issuecomment-2107925967
I think the artifacts were not published for non-js targets after `1.1.0`. If we add this only under JS settings, all is well.
Regarding build time, I think that was a bug potentially having to do with adding the dependency for all targets. For a full clean + build of core, the build time is now 28s on my machine.
I also went ahead and updated this as the executor under kyoTest. Do you think we need a direct dependency under kyo-core? I think transitive should be okay...
=> use: scala-js-macrotask-executor as ExecutionContext

build.sbt, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/InternalClock.scala
The removal of private is not 100% necessary, but intellij load cross projects by default as Scala 2. And when compiling Scala 2 it fails with an error that the class is exposed via a public method but it self is private. Which is actually a smell I guess.
Maybe both should be package private?
fixes #138 
/claim #138
=> Make kyo build with Intellij (#138)

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/SchedulerTest.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/WorkerTest.scala
When a worker gets blocked, Kyo's scheduler attempts to preempt the fiber but never dispatches a Java interrupt to the thread. This can be an issue in systems that rely on interruptions in blocking code since it can lead to significant accumulation of state, which can produce degradation.
I hadn't included this initially because Java interrupts are normally a headache but this seems to be a common practice in effect systems. In case of issues, it's also possible to disable the behavior by setting the config to `-1`.
=> scheduler: dispatch java interrupts

kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyoTest/fibersTest.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/KyoUtil.scala, kyo-tapir/shared/src/test/scala/kyoTest/server/NettyKyoServerTest.scala
Netty's future represents computations with result type `Void`, which is encoded at runtime as a `null` value. The code that integrates Kyo's fibers with Netty's wasn't considering this scenario and lifting the result directly to `T < IOs`. This PR fixes that by completing with a pending `IOs(null)` if Netty's Future completes with `null`, indicating the result of a `Void` computation.
I've also added a NPE guard in `fiber.complete` to make it easier to detect this issue since this is a low-level API meant for integration with other libraries.
=> kyo-tapir: fix netty future integration to consider Void completions

build.sbt
This seemed to be necessary to load in IntelliJ.
Turns out it was a bug and when
`Open cross-compiled Scala 3/Scala 2 projects as Scala 2` is unchecked,
it works as expected.
=> Remove double module definition of kyo scheduler zio

kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/test/scala/kyoTest/methodsTest.scala
This is necessary due to `Flat` now being derived from `Tag`s (#366). Not sure if there is a way we can bypass that only in some cases.
Rarely will effects ever need to be run with values that are intersection types, but for Layers (#203), this is definitely necessary.
=> fix: `.pure` when used with intersections types

kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala, kyo-core/shared/src/main/scala/kyo/internal/FlatImplicits.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/main/scala/kyo/typeMap.scala, kyo-core/shared/src/test/scala/kyoTest/methodsTest.scala, kyo-core/shared/src/test/scala/kyoTest/typeMapTest.scala, kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/tagsTest.scala, kyo-zio/shared/src/main/scala/kyo/zios.scala
The current `Tag` impl has unrelated representations for `Tag` (class types only) and set types (`Union` and `Intersection` of class types). This split has important limitations:
1. The `Envs` effect was [changed](https://github.com/getkyo/kyo/pull/424) by @hearnadam and @kitlangton recently to provide support for intersection types but it [required a hack](https://github.com/getkyo/kyo/blob/921c2f5738098c5a6245ac717d0dd3b9a47b0ab0/kyo-core/shared/src/main/scala/kyo/envs.scala#L12). To avoid the hack we'd need to support set tags in `core.handle` but it's not possible to implement that properly without a common type for the different kinds of tags.
2. The `Flat` check functions similarly to `Tag` since both reject types that don't represent concrete values. We could reimplement it in …
=> tags: improve interop with Union and Intersection

README.md
fixes #439
I'm not sure if this is the best thing to say. It seems vague enough that it is kinda true. I considered mentioning where others were used but it became too long and lost the point.
=> Reword note about the only macro in Kyo

kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala
As identified by @pablf in https://github.com/getkyo/kyo/pull/428#issuecomment-2138228061, `Streams` can end up producing nesting of effects due to the encoding using `opaque type`, which is unsound. This PR fixes it by using a wrapper class to hold the nested computation. It also can't be an `AnyVal` since we need the wrapper class at runtime to enable safe nesting.
An important lesson from this: it's not safe to alias Kyo computations directly via `opaque type`.
=> streams: fix nesting with other effects

kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/internal/Trace.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyoTest/internal/TraceTest.scala, kyo-core/shared/src/test/scala/kyoTest/methodsTest.scala, kyo-core/shared/src/test/scala/kyoTest/typeMapTest.scala, kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/tagsTest.scala, kyo-zio/shared/src/main/scala/kyo/zios.scala
The `toString` of Kyo computations currently print `<function1>`. This PR introduces a custom `toString` showing the details of the computation, including the new `Trace` information, to help aid in debugging and error reporting. I've also improved the bug error messages to use the new `toString`.
=> improve toString for Kyo computations + bug error messages

kyo-core/shared/src/main/scala/kyo/chunks.scala, kyo-core/shared/src/test/scala/kyoTest/chunksTest.scala
I noticed two `Chunk` bugs while working on https://github.com/getkyo/kyo/issues/368. `Chunk.changes` was ignoring the `first` param and `Chunk.copyTo` wasn't considering the offset correctly for appends.
=> chunk fixes

kyo-core/jvm/src/test/scala/kyoTest/MaybeMonadLawsTest.scala, kyo-core/shared/src/main/scala/kyo/Maybe.scala, kyo-core/shared/src/test/scala/kyoTest/MaybeTest.scala
The implementation matches the behavior of Scala's `Option`, even when there's nesting! The key insight is that nesting is only a problem when there are nested `Some(None)`, which the implementation tracks via cached internal `SomeNone` instances. The only scenarios where this implementation allocates objects is when the nesting of `Some(None)` exceeds `100` (quite unlikely) and when `Some.unapply` is used. I had to use Scala's `Option` for pattern matching because the compiler isn't able to locate `isDefined`/`get` as extension methods to consider `Some.unapply` an extractor.
I'm a bit uneasy about naming this new impl `Option` since it can be confusing to users but we have a precedence with `Duration`.
=> Maybe: allocationless Option (with nesting support!)

kyo-tag/shared/src/main/scala/kyo/internal/IntEncoder.scala, kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/internal/IntEncoderTest.scala
I noticed a performance regression introduced by https://github.com/getkyo/kyo/pull/432. The mechanism to decode `Int`s has to scan an array of chars, which introduces overhead and even allocations in some cases because `indexOf` is an unoptimized Scala implementation.
This PR fixes the regression by moving the search to compile time and producing a table that can be used with a simple offset lookup.
Benchmark results:
https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/872121366422a6cd4d1d19b9df1e95b9/raw/c4ccc79d42f61514c7fcdbdfc9ca12f4178caf67/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/872121366422a6cd4d1d19b9df1e95b9/raw/c4ccc79d42f61514c7fcdbdfc9ca12f4178caf67/jmh-result-candidate.json
=> tags: fix perf regression with int encoding

kyo-core/shared/src/main/scala/kyo/Result.scala, kyo-core/shared/src/test/scala/kyoTest/ResultTest.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/DB.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/Index.scala
Following a similar approach as https://github.com/getkyo/kyo/pull/464. The implementation can avoid allocations in case of success but has to allocate in case of failures.
=> Result (lightweight Try)

kyo-core/shared/src/main/scala/kyo/Duration.scala, kyo-core/shared/src/test/scala/kyoTest/DurationSpec.scala
I'm working on the changes to introduce the new core design but I'm having trouble with `<` now being a case class and the symbol conflicting with `<` from the `Duration` extension methods. This PR changes the encoding of `Duration` so the extension methods can be under the companion object instead of the package to avoid the conflict.
=> refactor Duration to avoid conflict with < in the new core

README.md, kyo-bench/src/main/scala/kyo/bench/ForkChainedBench.scala, kyo-bench/src/main/scala/kyo/bench/ForkManyBench.scala, kyo-bench/src/main/scala/kyo/bench/PingPongBench.scala, kyo-bench/src/main/scala/kyo/bench/RendezvousBench.scala, kyo-cache/shared/src/main/scala/kyo/caches.scala, kyo-combinators/shared/src/main/scala/kyo/constructors.scala, kyo-core/jvm/src/main/scala/kyo/fibersPlatformSpecific.scala, kyo-core/jvm/src/test/scala/kyoTest/completionStageTest.scala, kyo-core/shared/src/main/scala/kyo/channels.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/latches.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyoTest/channelsTest.scala, kyo-core/shared/src/test/scala/kyoTest/fibersTest.scala, kyo-core/shared/src/test/scala/kyoTest/loopsTest.scala, kyo-core/shared/src/test/scala/kyoTest/metersTest.scala, kyo-core/shared/src/test/scala/kyoTest/timersTest.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/KyoUtil.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/NettyKyoRequestBody.scala, kyo-zio/shared/src/main/scala/kyo/zios.scala, kyo-zio/shared/src/test/scala/kyo/ziosTest.scala
Fiber completions use `T < IOs` to avoid allocations but we have `Result` now that provides a proper solution for this use case and allows us to avoid `IOs.run` in a few places.
=> use Result for Fiber completions

build.sbt
Take 2.
Turns out it is actually quite easy to detect if the current workspace is a linked workspace because `.git` is a file instead of a directory.
=> Add workaround for git worktree

README.md
Hello,
This is my first contribution to this project. I noticed some inconsistencies in the documentation's heading levels under the Data Types section and decided to fix them.
Specifically, the headings for 'Maybe: Allocation-free Optional Values' and 'Result: Low-allocation Try Alternative' were updated from '##' to '###'. This change ensures a uniform structure and improves the readability of the documentation. No functional changes were made to the codebase.
Thank you for considering this pull request.
=> docs: Correct heading levels for Data Types sections

kyo-caliban/src/main/scala/kyo/schemas.scala, kyo-caliban/src/test/scala/kyo/resolversTest.scala
I copied the Cats Effect integration but it turns out [there was a bug in it](https://github.com/ghostdogpr/caliban/pull/2296) 😄
=> Fix field nullability in Caliban schema instances

.scalafmt.conf, build.sbt, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Regulator.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/top/Reporter.scala, kyo-scheduler/shared/src/test/scala-3/kyoTest/scheduler/TaskImplicits.scala, kyo-stats-registry/jvm/src/main/scala/kyo/stats/internal/StatsRefresh.scala, kyo-stats-registry/shared/src/main/scala/kyo/stats/internal/StatsRegistry.scala, project/plugins.sbt
Take 2.
Since starting this, the `-Wunused:all` option had been removed which makes things a bit easier.
FTR If we do need to ignore unused locals in a way that is compatible with Scala 2.12, 2.13 and 3 I think we can do this:
```
/**
* A way to ignore the unused warning that works in Scala 2.12, 2.13 and 3.
*/
@elidable(ASSERTION)
private[scheduler] def unused(a: => Any): Unit = {
val _ = a
()
}
```
=> Use Typelevel scalac-options

kyo-core/shared/src/main/scala/kyo/typeMap.scala, kyo-core/shared/src/test/scala/kyoTest/typeMapTest.scala
I colocated the extension methods so only `import kyo.TypeMap` is necessary for consumers.
I plan to add benchmarks comparing `ZEnvironment` next
=> add: TypeMap[A].prune[B]

kyo-core/shared/src/main/scala/kyo/chunks.scala, kyo-prelude/shared/src/main/scala/kyo2/Chunk.scala
I've been doing some performance testing as part of the work on the new core design and noticed thread contention when using chunks due to `ClassTag` lookups, which are synchronized by Scala's `ClassTag` cache. We don't really need the `ClassTag` lookup since the goal in chunks is to always use `Any` for internal arrays. I've tried to introduce a benchmark for it but I couldn't reproduce the issue in isolation.
I'm updating both versions in `kyo-core` and `kyo-prelude`.
=> chunks: avoid ClassTag cache lookup

kyo-prelude/jvm/src/test/scala/kyo2/kernel/BytecodeTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala
I'm working on providing a way to customize `Safepoint` with additional `enter` and `exit` implementations. The mechanism will be used for preemption in fibers but it can be easily extended to provide other features like profiling and debugging. This PR propagates the current value of the computation alongside its frame to `Safepoint.enter` as preparation. This will allow a custom `enter` to also inspect the current value. The main use case would be a `Debug` effect that also presents values that appear during execution.
**Edit**: I've pushed a commit with the new interceptor mechanism. `Safepoint.immediate` will be used by fibers to preempt execution in evaluation loop (suspension is managed by the fiber itself) and `Safepoint.propagating` provides similar functionality but ensuring …
=> prelude: safepoint interceptors

kyo-core/shared/src/test/scala/kyoTest/ResultTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/MonadLawsTest.scala, kyo-prelude/shared/src/main/scala/kyo2/Abort.scala, kyo-prelude/shared/src/main/scala/kyo2/Result.scala, kyo-prelude/shared/src/test/scala/kyo2/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo2/ChunkTest.scala, kyo-prelude/shared/src/test/scala/kyo2/EnvTest.scala, kyo-prelude/shared/src/test/scala/kyo2/ResultTest.scala
I'm working on porting `kyo-core` to `kyo-prelude` and part of the change introduces typed error handling for fibers. This PR makes `Result` a low-allocation mix of `Either` and `Try` to use it in fiber completions.
=> prelude: typed failures in Result

kyo-prelude/shared/src/main/scala/kyo2/Abort.scala, kyo-prelude/shared/src/main/scala/kyo2/Maybe.scala, kyo-prelude/shared/src/main/scala/kyo2/Result.scala, kyo-prelude/shared/src/test/scala/kyo2/ResultTest.scala
This PR introduces a few improvements. The main one is allocation-free pattern matching for both `Maybe` and `Result`. The new implicit class `Maybe.Ops` wraps a `Maybe` into an `AnyVal`, which satisfies the compiler to consider the method an extractor.
=> prelude: Maybe and Result improvements

kyo-prelude/shared/src/main/scala/kyo2/Var.scala, kyo-prelude/shared/src/test/scala/kyo2/VarTest.scala
Simplify the `Var.run` method to avoid the `Ops` class. The explicit type parameter isn't necessary since the `state` param already bounds the `V` type. I've also added a `Var.runTuple` method, which returns the value of the var with the result of the computation.
=> prelude: Var.run improvements

kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/PendingTest.scala
I'm using both methods to implement fibers based on `kyo-prelude`. 
The `evalNow` method inspects if the computation has no pending effects to return its value if possible (via `Maybe`). In fibers, this method is used to avoid forking computations that are already complete. I'm wasn't sure about keeping this method public since it's low-level but it seems useful to allow users and library authors to implement logic that avoids overhead in case the computation is already complete.
The `evalPartial` is used from the `IOTask` effect handling to install the interceptor and stop evaluation once the interceptor signals to stop (preemption in fibers).
=> prelude: add `evalNow` and `evalPartial` methods to the pending type

.github/workflows/release.yml
I'm not sure why the build on main is always failing due to the release job. I think something might have changed in Sonatype. I'd like to disable it for now as a workaround. We'll have to address this issue before the next release.
=> disable release workflow for now

kyo-prelude/shared/src/main/scala/kyo2/Abort.scala, kyo-prelude/shared/src/main/scala/kyo2/Choice.scala, kyo-prelude/shared/src/main/scala/kyo2/Env.scala, kyo-prelude/shared/src/main/scala/kyo2/Local.scala, kyo-prelude/shared/src/main/scala/kyo2/Sum.scala, kyo-prelude/shared/src/main/scala/kyo2/Var.scala, kyo-prelude/shared/src/main/scala/kyo2/internal/BaseKyoTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Frame.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/test/scala/kyo2/KyoTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/FrameTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/TraceTest.scala
I had thought that we wouldn't need to pass `Frame` explicit in methods marked as `inline` but that's not the the case. Instead of using the frame from the outer call, the compiler summons a new one. This PR introduces the `Frame` implicit to inline methods, reduces the size of the frame payload by inferring the short snippet from the expanded one, and introduces a few other improvements (some unrelated to tracing)
=> prelude: tracing fixes and improvements

kyo-prelude/jvm/src/test/scala/kyo2/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/PendingTest.scala
This PR introduces `Safepoint.ensure` to be used from `IO.ensure`. It ensures the execution of a thunk at the end of the computation even if the computation fails. In case an `Interceptor` is used to preempt execution (like in `IOTask`), the interceptor can also collect the thunks of the `ensure` calls to execute them later. It's a mechanism [similar](https://github.com/getkyo/kyo/blob/14c1d921441bfd23279434559e7da9e5987e2c5f/kyo-core/shared/src/main/scala/kyo/ios.scala#L89) to the current core.
This seems to be the last feature we need to port `kyo-core` to the new design! \o/
=> prelude: add Safepoint.ensure

kyo-prelude/shared/src/main/scala/kyo2/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala
I introduced `KyoContinue` late in the development of `kyo-prelude` and didn't update all classes to use it. It reduces the bytecode size by moving the `tag` and `input` fields to a shared super class.
=> use KyoContinue to reduce bytecode size

kyo-prelude/js/src/main/scala/java/lang/ThreadLocal.scala, kyo-prelude/jvm/src/test/scala/kyo2/MonadLawsTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/kernel/BytecodeTest.scala, kyo-prelude/shared/src/main/scala/kyo2/Aspect.scala, kyo-prelude/shared/src/main/scala/kyo2/Choice.scala, kyo-prelude/shared/src/main/scala/kyo2/Chunk.scala, kyo-prelude/shared/src/main/scala/kyo2/Env.scala, kyo-prelude/shared/src/main/scala/kyo2/Kyo.scala, kyo-prelude/shared/src/main/scala/kyo2/Local.scala, kyo-prelude/shared/src/main/scala/kyo2/Result.scala, kyo-prelude/shared/src/main/scala/kyo2/Sum.scala, kyo-prelude/shared/src/main/scala/kyo2/TypeMap.scala, kyo-prelude/shared/src/main/scala/kyo2/internal/BaseKyoTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/package.scala, kyo-prelude/shared/src/main/scala/kyo2/package.scala, kyo-prelude/shared/src/test/scala/kyo2/KyoTest.scala, kyo-prelude/shared/src/test/scala/kyo2/ResultTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/TraceTest.scala
- Updates all generics to the new naming strategy
- Adds missing `Frame` implicits
- Introduces convenience `Result.unit` method.
=> prelude: misc improvements and fixes

kyo-prelude/jvm/src/test/scala/kyo2/kernel/BytecodeTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/EffectTest.scala
I'm doing some performance testing and noticed a regression due to the `Effect.handle*` methods of the new kernel not being tail-recursive when there are multiple suspensions of the same effect. I hadn't noticed this issue yet because the new safepoint mechanism prevents stack overflows.
=> make Effect.handle* methods partially tail-recursive

kyo-prelude/shared/src/main/scala/kyo2/Local.scala, kyo-prelude/shared/src/test/scala/kyo2/LocalTest.scala
When working with KyoApp locally, I noticed that SLF4J was being initialized even when I was providing a Local value to override it from the very start. This should prevent that behavior at some cost to the first access.
@fwbrasil if you prefer, I can create an `initLazy`.
=> Lazily initialize `default` in `Local`

build.sbt, kyo-bench/src/main/scala/kyo/bench/StateBench.scala, kyo-bench/src/main/scala/kyo/bench/StateMapBench.scala
These benchmarks reproduce the issue reported in #531 and are inspired in the implementations in https://github.com/marcinzh/effect-zoo. Kyo's performance is ahead for the regular use of `Var` but the scenario with an additional `map` after the recursion shows a performance issue. This behavior is due to Kyo's encoding of effect suspension, which introduces more overhead due to the large number of suspensions that have to accumulate the `map` transformation. The scenario seems atypical but it can be useful to uncover new optimizations.
[Benchmark results](https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/089284da94a4d5024392548d31e2446f/raw/5d3b7e4076898d3852f703cc7663f5a432773c1d/jmh-result.json):
=> state benchmarks

kyo-prelude/jvm/src/test/scala/kyo2/MonadLawsTest.scala, kyo-prelude/shared/src/main/scala/kyo2/Var.scala, kyo-prelude/shared/src/test/scala/kyo2/ChunkTest.scala, kyo-prelude/shared/src/test/scala/kyo2/VarTest.scala
I'm taking a look at the profiling session for https://github.com/getkyo/kyo/issues/531 and noticed that we can avoid the allocation of `Input.Set`. This PR updates the effect to use a union type for its input, introduces new APIs, and includes scaladocs (you read that right 😅)
=> prelude: Var improvements

kyo-prelude/shared/src/main/scala/kyo2/Kyo.scala, kyo-prelude/shared/src/main/scala/kyo2/Stream.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Loop.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/LoopTest.scala
This PR introduces an optimization to specialize `Continue*` instances. They're currently generic, which requires boxing of primitive types in the `Continue` instance fields. After this change, the fields in the final bytecode are specialized. Example from a decompiled loop:
```java
new Loop.Continue2<String, Object>(i1, i2){
private final String i1$tailLocal1$1;
private final int i2$tailLocal1$1;
```
There's still boxing when the value is recovered in the generic scope of the `Loop` body but that's something the JIT can easily optimize.
I'm also using abbreviated generic names. It makes it easier for me to read the code but I'd be ok to moving back to more descriptive names. The `Loop.transform*` methods are renamed to `Loop.apply*` to improve readability since `transform` doesn't seem …
=> prelude: Loop improvements

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/WorkerTest.scala
I noticed some performance overhead while working on the new fiber implementation because workers keep draining over and over. This PR replaces the `running` flag in `Worker` by a proper `State` object. After this change, workers get drained only once when they transitioning from `Running` to `Stalled`.
=> scheduler: avoid draining workers multiple times

kyo-prelude/shared/src/main/scala/kyo2/Emit.scala, kyo-prelude/shared/src/test/scala/kyo2/EmitTest.scala
I'm working on adding the `IO`-based features of `Stream` as extension methods in the new `kyo-core` based on `kyo-prelude`. `Emit.runAck` will be used to implement `Stream.buffer`.
=> prelude: introduce Emit.runAck

kyo-prelude/jvm/src/test/scala/kyo2/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Context.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Trace.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/package.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/BoundaryTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/ContextTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/EffectTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/PendingTest.scala
This seems to be the last optimizations needed to port `kyo-core` to the new design. I had designed a generic `Boundary` mechanism that could be used even by user-defined effects but the abstraction requires a few allocations in the critical path of the the fiber execution (`IOTask`). I'm kind of throwing the towel for now and providing more low-level APIs designed specifically to ensure peak performance for fibers.
=> prelude: optimizations for IOTask

kyo-prelude/shared/src/main/scala/kyo2/Ansi.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Frame.scala, kyo-prelude/shared/src/test/scala/kyo2/AnsiTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/FrameTest.scala
This PR introduces a basic syntax highlight mechanism to improve the rendering of frames. Example output of `frame.show`:
```scala
object main extends App:
def myMethod(i: Int)(using f: Frame) = f
val f =
myMethod(Math.pow(1, 0).toInt)
println(f.show)
end main
```
=> ansi frame rendering

kyo-prelude/shared/src/main/scala/kyo2/Ansi.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Trace.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/TraceTest.scala
Traces use a circular buffer internally to store frames, which can make the first frame to land in any index of the array, not necessarily at index `0`. This PR fixes `Trace.Owner.enrich` to consider this scenario correctly.
=> prelude: fix use of the Trace circular buffer in Trace.Owner.enrich

kyo-prelude/jvm/src/test/scala/kyo2/MonadLawsTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/kernel/BytecodeTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo2/Abort.scala, kyo-prelude/shared/src/main/scala/kyo2/Emit.scala, kyo-prelude/shared/src/main/scala/kyo2/Env.scala, kyo-prelude/shared/src/main/scala/kyo2/Kyo.scala, kyo-prelude/shared/src/main/scala/kyo2/Maybe.scala, kyo-prelude/shared/src/main/scala/kyo2/Memo.scala, kyo-prelude/shared/src/main/scala/kyo2/Result.scala, kyo-prelude/shared/src/main/scala/kyo2/TypeMap.scala, kyo-prelude/shared/src/main/scala/kyo2/Var.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Context.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Flat.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Loop.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala, kyo-prelude/shared/src/main/scala/kyo2/package.scala, kyo-prelude/shared/src/test/scala/kyo2/KyoTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/FlatTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/PendingTest.scala
I'm porting the other modules to the new design in `kyo-prelude` but there's a performance regression that I can't see how to avoid with the new encoding in the current version of the Scala 3 compiler:
- Given the lack of specialization, the generated bytecode contains a significant amount of unexpected `<` boxing. Fortunately, the JIT is able to avoid most of these allocations but profiling sessions show `<` allocations in several benchmarks. It isn't a bottleneck in the benchmarks I analyzed but introduces some overhead.
- The compiler doesn't allow implementing interfaces with `AnyVal` generic type parameters. As a workaround, I was planning to use a wrapper class like in `MonadLawsTest` but the approach is too expensive in integrations like in `kyo-sttp`. The wrapper class essentially …
=> prelude: revert pending type encoding to an opaque type

README.md, build.sbt
Following up on https://github.com/getkyo/kyo/pull/572, this PR fixes the readme to incorporate the changes in the new core design. This is only an initial pass fixing the code examples. I'm planning to follow up with a more comprehensive documentation review but I think we can do that after we have a release with the new design out.
=> fix readme

README.md, kyo-bench/src/main/scala/kyo/bench/CollectBench.scala, kyo-bench/src/main/scala/kyo/bench/ForkJoinBench.scala, kyo-bench/src/main/scala/kyo/bench/ForkJoinContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/MtlBench.scala, kyo-bench/src/main/scala/kyo/bench/SchedulingBench.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-core/jvm/src/test/scala/kyo/PathTest.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/stats/internal/TraceReceiver.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala, kyo-prelude/shared/src/main/scala/kyo/Choice.scala, kyo-prelude/shared/src/main/scala/kyo/Chunk.scala, kyo-prelude/shared/src/main/scala/kyo/Kyo.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/ChunkTest.scala, kyo-prelude/shared/src/test/scala/kyo/KyoTest.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala, kyo-tapir/shared/src/main/scala/kyo/routes.scala
This PR makes `Chunk` extend from `Seq` so we can avoid additional allocations to transform between the types and improve usability. It's not ideal since Scala's `Seq` methods aren't well-optimized but it seems a good tradeoff.
The methods that used to take effectful functions like `map` and `filter` were moved to `Kyo.*` and the methods from `Kyo.seq.*` are now available directly in `Kyo.*`.
=> make Chunk a Seq

kyo-prelude/shared/src/main/scala/kyo/kernel/ContextEffect.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/ContextEffectTest.scala
A minor API improvement providing an overloaded method `ContextEffect.handle` that takes a constant value instead of `ifDefined`/`ifUndefined`.
=> ContextEffect.handle for constant values

build.sbt, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/test/scala/kyo/EffectCombinatorTest.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-data/shared/src/main/scala/kyo/Result.scala, kyo-prelude/shared/src/main/scala/kyo/debug/Debug.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Frame.scala, kyo-prelude/shared/src/test/scala/kyo/debug/DebugTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/FrameTest.scala
This new effect uses the `Safepoint.Interceptor` mechanism introduced by https://github.com/getkyo/kyo/pull/489 and the code snippets captured by `Frame` to output debugging information. The `Debug.apply` method only logs the result of the computation with its frame while `Debug.trace` outputs all transformations of a computation with their values. 
There's an important limitation: the `Safepoint.Interceptor` currently isn't propagated to forked fibers so the debugging won't output the trace of computations in forked fibers. I'll follow up on this limitation but it's a bit tricky because we need to avoid increasing the memory footprint of `IOTask`.
Example output of `Debug.trace`:
=> debug effect

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/test/scala/kyo/EnvCombinatorTest.scala, kyo-combinators/shared/src/test/scala/kyo/FiberCombinatorTest.scala, kyo-prelude/shared/src/main/scala/kyo/Env.scala, kyo-prelude/shared/src/test/scala/kyo/LayerTest.scala
Also separated `provideValue` and` provideLayer` from provide in kyo-combinators. `provide` now provides all layers, just like in ZIO
=> Env.runLayer can handle effects introduced by layers

.github/workflows/release.yml
The split of the project into `kyoJVM` and `kyoJS` by https://github.com/getkyo/kyo/pull/450 made the release workflow not publish JS artifacts since only `kyoJVM` is selected by default.
=> fix release of JS artifacts

README.md
*Async.init* is a non-existent function. *Async.run* is the real one.
=> fix typo in Async section

kyo-prelude/shared/src/main/scala/kyo/prelude.scala
I noticed this new warning after https://github.com/getkyo/kyo/pull/614. It seems the compiler wa ignoring the methods in `kyo-data` and the change exposed the issue.
```
[info] compiling 32 Scala sources to /Users/fwbrasil/workspace/kyo/kyo-core/jvm/target/scala-3.5.0/classes ...
[warn] Toplevel definition isNull is defined in
[warn]   /Users/fwbrasil/workspace/kyo/kyo-prelude/jvm/target/scala-3.5.0/classes/kyo/prelude$package.tasty
[warn] and also in
[warn]   /Users/fwbrasil/workspace/kyo/kyo-data/jvm/target/scala-3.5.0/classes/kyo/data$package.tasty
[warn] Keeping only the definition in /Users/fwbrasil/workspace/kyo/kyo-prelude/jvm/target/scala-3.5.0/classes/kyo/prelude$package.tasty
Warning: mocking up superclass for module class kernel
[warn] one warning found
```
=> fix compilation warning due to duplicate package methods

kyo-prelude/jvm/src/test/scala/kyo/kernel/BytecodeTest.scala, kyo-prelude/jvm/src/test/scala/kyo/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Safepoint.scala
`Safepoint.enter` is the hottest code in Kyo after the migration to the new design. This PR reduces its overhead by packing multiple fields into a single `Long`. Benchmark results:
https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/dbce289b4c7e98c3146637ed5f386e1a/raw/1c557d8bc06727d0aea9f8e4170d007846e0eafa/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/dbce289b4c7e98c3146637ed5f386e1a/raw/1c557d8bc06727d0aea9f8e4170d007846e0eafa/jmh-result-candidate.json
=> kernel: safepoint optimizations

kyo-prelude/shared/src/main/scala/kyo/kernel/Effect.scala
The method invokes `Safepoint.enter` twice: once by `Safepoint.handle` and another time by the `.map` call. We lose a bit of information because the frame with show up only after the `handle` call but it seems a reasonable tradeoff.
Results for related benchmarks:
https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/22b12ca7fe9c4175ce9aeb00086d3a5d/raw/3f5c5f410f14434b72fc18e4a3d9866b377413ad/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/22b12ca7fe9c4175ce9aeb00086d3a5d/raw/3f5c5f410f14434b72fc18e4a3d9866b377413ad/jmh-result-candidate.json
=> kernel: optimize Effect.handle.state

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Admission.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Concurrency.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Regulator.scala
I noticed some boxing allocations in regulators. Since Scala 3 doesn't have specialization yet, I'm using Java's supplier interfaces. This is a minor cleanup since the allocation rate is low.
=> scheduler: avoid primitive boxing in regulators

README.md, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/PendingTest.scala
This PR introduces overloaded `pipe` methods for up to six functions similarly to EffectTS but it's a method on the pending type, not in a companion object https://effect.website/docs/guides/essentials/pipeline
=> kernel: EffectTS-inspired 'pipe' methods

kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-bench/src/main/scala/kyo/bench/WarmupJITProfile.scala, kyo-bench/src/test/scala/kyo/benchTest/CatsBenchTest.scala, kyo-bench/src/test/scala/kyo/benchTest/KyoBenchTest.scala, kyo-bench/src/test/scala/kyo/benchTest/ZIOBenchTest.scala
A major downside of microbenchmarks in a JIT-compiled runtime like the JVM is how the execution can be extremely different from how the code would behave in a real application. This happens because benchmarks typically use a very narrow subset of the code and the profiling information collected by the JVM to generate optimized native code doesn't represent well how the code is actually used.
This PR introduces a warmup mechanism that executes several of the existing benchmarks to populate the JIT profile with more realistic information. I did just an initial analysis of Kyo's results and created https://github.com/getkyo/kyo/pull/620 but I'm planning to continue working on it. The mechanism is disabled by default for now.
=> bench: introduce JIT profile warmup mechanism

README.md, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/test/scala/kyo/ClockTest.scala, kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala
I'm planning to use the deadline API to fix `Async.block` that should use `Clock` instead of Java's `System` directly.
=> core: Clock stopwatch, deadline, and unsafe APIs

kyo-data/shared/src/main/scala/kyo/Result.scala, kyo-data/shared/src/test/scala/kyo/ResultTest.scala
I found myself needing to manually match on `error: Error[E] @unchecked`...
=> Result: add unified Error.unapply

README.md
It seems important to highlight this since users might try the library with IntelliJ, which currently doesn't provide the experience Kyo is designed for.
=> readme: IDE support

kyo-prelude/shared/src/main/scala/kyo/Abort.scala
=> prelude: remove unused type param from Abort.run (#680)

kyo-cats/js/src/test/scala/java/util/concurrent/CountDownLatch.scala, kyo-cats/shared/src/test/scala/kyo/CatsTest.scala, kyo-zio/js/src/test/scala/java/util/concurrent/CountDownLatch.scala, kyo-zio/shared/src/test/scala/kyo/ZIOsTest.scala
The recent CI instability with the `cats-effect` tests is a symptom of a bug. I was expecting the interruption thunk provided to `IO.async` to be evaluated independently of the fiber yielding the execution to the scheduler but that's not the case. Additionally, interruptions from Kyo aren't being propagated to cats-effect.
This issue wasn't detected earlier because the tests copied from `kyo-zio` were incorrect. For ZIO, the interruption from ZIO to Kyo via the provided thunk to `ZIO.asyncInterrupt` is working properly but propagating interruptions from Kyo to ZIO is also not working.
This PR fixes the tests to show the issue.
=> cats/zios: reproduce interruption issues

README.md, build.sbt, kyo-bench/src/main/scala/kyo/bench/ForkChainedBench.scala, kyo-bench/src/main/scala/kyo/bench/TagsBench.scala, kyo-core/jvm/src/main/scala/kyo/Process.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Log.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Reducible.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Queue.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Regulator.scala, kyo-stats-otel/shared/src/main/scala/kyo/stats/otel/OTelTraceReceiver.scala, kyo-tapir/shared/src/main/scala/kyo/server/NettyKyoServer.scala
The compiler needs this other flag to detect the issue discussed in https://github.com/getkyo/kyo/pull/685. I've fixed the warnings and didn't notice bugs besides the expected ones in `Async.scala`
=> build: enable nonunit-statement compiler option

kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala
A solution for https://github.com/getkyo/kyo/issues/689 inspired by @steinybot's approach using a type class in https://github.com/getkyo/kyo/pull/692. I noticed that it's possible to simplify it by encoding only the necessary runtime information in the type class instead of the actual method implementation.
=> prelude: support handling Abort[Nothing]

kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-cats/shared/src/test/scala/kyo/CatsTest.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala, kyo-zio/shared/src/test/scala/kyo/ZIOsTest.scala
I noticed that https://github.com/getkyo/kyo/pull/666 missed tests for `fiber.mapResult` and, when I added them, it reproduced a bug. I've also introduced added a new `IOPromiseTest` that was missing, which also uncovered a bug with `interrupts`.
=> core: async fixes

kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala
Introduces a feature similar to `uninterruptible` in other effect systems. It's a mechanism similar to `IO.ensure` but encoded in the async execution.
=> core: async masking

README.md, kyo-caliban/src/main/scala/kyo/Resolvers.scala, kyo-caliban/src/main/scala/kyo/Schema.scala, kyo-caliban/src/test/scala/kyo/ResolversTest.scala, kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-cats/shared/src/test/scala/kyo/CatsTest.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala, kyo-zio/shared/src/test/scala/kyo/ZIOsTest.scala
Fixes #682
The current encoding of the integrations with ZIO and cats-effect uses custom effects and Kyo's Async has limitations to fork computations with arbitrary pending effects. This PR changes `get` to be based directly on `Async` but keeps the `run` method to interpret Kyo computations to the other effect systems.
This approach was explored in collaboration with @hearnadam
=> new encoding for zio and cats-effect integrations

kyo-prelude/shared/src/main/scala/kyo/Kyo.scala, kyo-prelude/shared/src/test/scala/kyo/KyoTest.scala
The new method is needed to optimize `Batch` and I've changed the collection methods to propagate safepoints like in https://github.com/getkyo/kyo/pull/720
=> prelude: introduce Kyo.foreachIndexed + propagate safepoints

kyo-prelude/shared/src/main/scala/kyo/kernel/Loop.scala
Kyo's `Safepoint` mechanism is responsible for providing stack safety, tracing, and interceptors for features like preemption and the `Debug` effect. The `Safepoint` is held in a `ThreadLocal` but, given that every transformation in Kyo has to use it, always reading from the `ThreadLocal` can introduce significant performance overhead. To mitigate it, Kyo's kernel also propagates the safepoint via implicits but the `Loop` implementation is missing it.
=> prelude: propagate safepoints in Loop

kyo-prelude/shared/src/main/scala/kyo/Batch.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Flat.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/FlatTest.scala
Addressing a TODO. The `Flat` macro was incorrectly not considering existing evidences in scope.
=> prelude: Flat macro fix

kyo-cache/shared/src/main/scala/kyo/Cache.scala, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-combinators/shared/src/test/scala/kyo/ChoiceCombinatorTest.scala, kyo-combinators/shared/src/test/scala/kyo/ConstructorsTest.scala, kyo-combinators/shared/src/test/scala/kyo/EffectCombinatorTest.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-prelude/jvm/src/test/scala/kyo/MonadLawsTest.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo/VarTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/PendingTest.scala
Fixes #650
Some of the methods I still kept receiving effectful parameters and I've also promoted `as` to the pending type since it's a common pattern.
=> combinators: avoid effectful parameters

kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/jvm/src/main/scala/kyo/internal/FiberPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala
Cleanup to replace `Unit` with `Discard` in methods that discard the result of the operation
=> core: avoid Unit suffix in method names

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/ClockTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala
The `Async.scala` file is getting too large and it's likely we'll have to extend the provided APIs. This PR moves `Fiber` and `Promise` to a separate file. I've also taken the opportunity to fix `fiber.block` to use the provided `Clock` in the environment using the new unsafe APIs.
=> core: Async cleanups

kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-core/jvm/src/main/scala/kyo/internal/FiberPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala
Now that we have unsafe APIs for `Fiber` and `Promise`, there shouldn't be direct use of `IOPromise` in other places of the codebase.
=> core: cleanup direct use of IOPromise

kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala
As pointed out by @hearnadam in https://github.com/getkyo/kyo/pull/707, the fiber returned by `mask` doesn't propagate interrupts to its previous steps but the instance itself can still be interrupted. It's a behavior that is different from other effect systems and makes the masking feature less useful. This PR fixes that by using a custom `IOPromise` class with a method override.
=> core: make masked IOPromise not interruptible

kyo-prelude/shared/src/main/scala/kyo/Batch.scala, kyo-prelude/shared/src/test/scala/kyo/BatchTest.scala
[Benchmark results](https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/5eae45217e6646aa77c193d081093920/raw/07acdb06bb3cf53faa466581f32cbd971afb47c0/jmh-result.json) with this change on top of https://github.com/getkyo/kyo/pull/718 and the other recent optimizations.
=> prelude: Batch optimizations

kyo-core/shared/src/main/scala/kyo/scheduler/Finalizers.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-prelude/jvm/src/test/scala/kyo/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo/debug/Debug.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Safepoint.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/ArrowEffectTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/BoundaryTest.scala
The term "ensure" came from the `IO.ensure` method and seems too opaque regarding its purpose.
=> prelude/core: rename Ensures to Finalizers

kyo-core/shared/src/main/scala/kyo/Adder.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Console.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/Random.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-core/shared/src/main/scala/kyo/Timer.scala, kyo-core/shared/src/main/scala/kyo/stats/internal/Span.scala
The unsafe warnings are not showing up in scaladocs because they're formatted as a regular comment. I've also added the warning to a few APIs that were missing it.
=> core: fix unsafe APIs scaladocs

README.md
It points to the latest version: https://javadoc.io/doc/io.getkyo/kyo-core_3
=> readme: javadoc badge

kyo-data/shared/src/main/scala/kyo/SafeClassTag.scala, kyo-data/shared/src/main/scala/kyo/internal/SafeClassTagMacro.scala, kyo-data/shared/src/test/scala/kyo/SafeClassTagTest.scala
So it's possible to provide a `CanEqual` evidence.
=> data: use Set to represent unions and intersections in SafeClassTag

build.sbt, project/plugins.sbt
Maintaining binary compatibility will be an important aspect once we reach `1.0`. This PR introduces [mima](https://github.com/lightbend-labs/mima) but configured to only produce warnings for now. I'm planning to keep an eye on it to have a better understanding of what will take to maintain binary compatibility and identify patterns we could follow to make the process easier. We should eventually also adopt [tasty-mima](https://github.com/scalacenter/tasty-mima) but I couldn't find a way to make it only warn of issues.
=> build: configure mima binary checks

README.md, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-combinators/shared/src/test/scala/kyo/AbortCombinatorTest.scala, kyo-combinators/shared/src/test/scala/kyo/ConstructorsTest.scala, kyo-combinators/shared/src/test/scala/kyo/EffectCombinatorTest.scala, kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-core/shared/src/main/scala/kyo/scheduler/Finalizers.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala, kyo-core/shared/src/test/scala/kyo/SystemTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala, kyo-data/shared/src/main/scala/kyo/Maybe.scala, kyo-data/shared/src/test/scala/kyo/MaybeTest.scala, kyo-data/shared/src/test/scala/kyo/ResultTest.scala, kyo-direct/shared/src/test/scala/kyo/DirectTest.scala, kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/main/scala/kyo/Memo.scala, kyo-prelude/shared/src/main/scala/kyo/internal/LayerMacros.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/EnvTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/PendingTest.scala
I sometimes avoid pattern matching on `Maybe` because it feels too verbose. This PR exports `Maybe.Empty` and `Maybe.Defined` as members in the `kyo` package. It also reduces the syntax overhead for tracking `Abort[Empty]`. It seems reasonable since the type names shouldn't conflict with common types.
=> data: Rename Maybe.Defined/Empty to Present/Absent and export them to the kyo package

kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/main/scala/kyo/Kyo.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/KyoTest.scala
I took a look at ZIO's error handling as part of https://github.com/getkyo/kyo/issues/651 and it's essentially based on user-defined runtime pattern matching without a mechanism like Kyo's to safely handle multiple failure types at once via tags. I'm not sure there's much we can incorporate from ZIO but something that is a major advantage is how easy it is to recover and transform errors in ZIO compared to Kyo. Users currently need to use `Abort.run`, which returns a `Result`, and then perform additional transformations.
This PR introduces `Abort.recover` to directly recover specific failures. It provides two versions:
1. `Abort.recover[FailureType](onFail)(computation)`: Only handles `Fail` suspensions and leaves a pending `Abort[Nothing]` in case of panics.
2. …
=> prelude: introduce Abort.recover and Kyo.pure

README.md, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/test/scala/kyo/EffectCombinatorTest.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-core/shared/src/test/scala/kyo/RetryTest.scala, kyo-data/shared/src/main/scala/kyo/Duration.scala, kyo-data/shared/src/main/scala/kyo/Instant.scala, kyo-data/shared/src/main/scala/kyo/Schedule.scala, kyo-data/shared/src/test/scala/kyo/DurationSpec.scala, kyo-data/shared/src/test/scala/kyo/InstantTest.scala, kyo-data/shared/src/test/scala/kyo/ScheduleTest.scala
Inspired by ZIO's `Schedule` but as pure data structure.
=> data: Schedule

kyo-bench/src/main/scala/kyo/bench/CollectParBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientRaceContentionBench.scala, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Boundary.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/BoundaryTest.scala
As mentioned in https://github.com/getkyo/kyo/pull/765/files#r1807072333, the inference of `Boundary` in `Async` is failing when the compiler infers a widened `Abort` from the return type of an operation. This issue is also affecting [easyracer](https://github.com/jamesward/easyracer).
=> prelude/core: fix boundary inference with Abort

kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala
We recently changed fibers to propagate interrupts separate from completions (see `IOPromise`'s `onComplete` vs `onInterrupt`) but forgot to update `Fiber.race` to ensure loser fibers are interrupted. Since the `interrupts` link now only triggers if there's an interruption, which isn't the case if a fiber wins the race, all raced fibers are running to completion.
=> core: fix Fiber.race interrupts

kyo-core/js/src/main/scala/kyo/internal/LogPlatformSpecific.scala, kyo-core/jvm/src/main/scala/kyo/internal/LogPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala, kyo-core/shared/src/test/scala/kyo/LogTest.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/DB.scala
Following up on https://github.com/getkyo/kyo/pull/780#discussion_r1818130462
=> [core] Log improvements

kyo-tapir/shared/src/main/scala/kyo/server/NettyKyoServer.scala
Tests that start a tapir server are taking ~2s to finalize because Netty waits for some time before shutting down. This PR makes the shut down process respect the timeout defined by the user.
=> [tapir] propagate shutdown timeout to netty

kyo-data/shared/src/main/scala/kyo/Text.scala, kyo-data/shared/src/test/scala/kyo/TextTest.scala
This PR introduces `Text` in `kyo-data` to provide more efficient handling of `String` operations. The main optimization is representing substrings via a `Cut` wrapper instead of copying strings.
This is part of the work to introduce a new `Parse` effect in `kyo-prelude` using effect handling for a more convenient backtracking mechanism.
=> data: Text

build.sbt
This option avoids Metals loading non-JVM modules, which causes intermittent issues to execute tests from the IDE.
=> [build] disable BSP for non-JVM modules

kyo-core/shared/src/main/scala/kyo/IO.scala
Inlining this to user code will produce the error:
```
class Ensure cannot be accessed as a member of (Safepoint$_this : ($proxy15 : kyo.kernel.Safepoint.type{type State = Long})) from anonymous class Safepoint$_this.Ensure {...}.
private[kyo] class Ensure can only be accessed from package kyo.
```
=> IO.ensure: avoid inlining `private[kyo]` class

kyo-bench/src/main/scala/kyo/bench/HttpClientRaceContentionBench.scala
The benchmark is failing for both Kyo and ZIO. This PR comments out the benchmark as a workaround for now so we can can run the benchmark suite in CI
=> [bench] disable HttpClientRaceContentionBench

kyo-data/shared/src/main/scala/kyo/Tag.scala, kyo-data/shared/src/main/scala/kyo/Text.scala, kyo-data/shared/src/test/scala/kyo/TextTest.scala, kyo-prelude/shared/src/main/scala/kyo/Parse.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Flat.scala, kyo-prelude/shared/src/test/scala/kyo/ParseTest.scala, kyo-prelude/shared/src/test/scala/kyo/Test.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/FlatTest.scala
Provides parsing capabilities with backtracking and lookahead support. The effect assumes there's an input string in scope (`Var`) being parsed and operations consume from it, evaluating multiple possible branches with `Choice` and failing with `Abort` if necessary. It's also possible to mix other effects with `Parse`.
=> [prelude] Parse effect

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-sttp/shared/src/test/scala/kyo/internal/KyoSttpMonadTest.scala
Easyracer is having trouble with Kyo not interrupting requests on timeout. It's a bug similar to https://github.com/getkyo/kyo/pull/771. `Async.timeout` is only propagating a completion, which isn't enough to interrupt execution now that we split regular completions from interruptions.
This PR changes `IOPromise.interrupt` and related methods to allow an `Error[E]` so it's possible to interrupt the execution with a `Result.Fail(timeoutError)` in `Async.timeout` instead of a `Panic`.
=> [core][sttp] fix timeout interruption

kyo-core/shared/src/main/scala/kyo/Adder.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Console.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Stat.scala, kyo-core/shared/src/main/scala/kyo/stats/attributes.scala
Following up on https://github.com/getkyo/kyo/pull/800#discussion_r1824897284. Since Scala 3 doesn't have specialization `AnyVal` values can keep boxing on every transformation.
=> [core] avoid AnyVal

kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Boundary.scala
I couldn't find a fix for https://github.com/getkyo/kyo/issues/804. We might need to restructure how we encode boundaries to support it. This PR adds pending tests and better error reporting in case of issues to infer the boundary.
=> [core] reproduce issue with nested boundaries + provide better error messages

kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-data/shared/src/main/scala/kyo/Ansi.scala, kyo-prelude/shared/src/main/scala/kyo/Local.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Context.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/ContextEffect.scala, kyo-prelude/shared/src/test/scala/kyo/LocalTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/BoundaryTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/ContextTest.scala
Kyo's `Meter`s are currently non-reentrant. That's not an ideal default because it can easily lead to deadlocks. If a fiber tries to obtain the same mutex multiple times for example, it won't ever resume. This PR is the initial step to enable reentrancy by providing a new mechanism that isolates locals so they aren't inherited by forked fibers.
The solution uses a new `ContextEffect.Isolated` marker trait to filter entries from `Context` when a computation is being forked via a `Boundary`. The `Local` implementation uses two effect types to differentiate locals that are isolated or not.
With this new mechanism, I'm planning to change `Meter` to propagate an isolated local indicating that the fiber is currently holding a permit for a specific meter. Since locals are scoped, they will be …
=> [prelude][core] isolated locals and reentrant meters

kyo-core/jvm/src/main/scala/kyo/internal/LogPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/Closed.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/Timeout.scala, kyo-data/shared/src/main/scala/kyo/Ansi.scala, kyo-prelude/jvm/src/test/scala/kyo/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo/Batch.scala, kyo-prelude/shared/src/main/scala/kyo/Check.scala, kyo-prelude/shared/src/main/scala/kyo/Local.scala, kyo-prelude/shared/src/main/scala/kyo/Parse.scala, kyo-prelude/shared/src/main/scala/kyo/debug/Debug.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Frame.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Trace.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/package.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/FrameTest.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala
I noticed a major performance regression in `LoggingBench`. The main cause is a bug introduced by https://github.com/getkyo/kyo/pull/783 that makes the benchmark consider `Level.error` enabled when it isn't. I fixed the bug but also worked on a few optimizations to improve performance in case the log is enabled.
Benchmark [results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/b7686518b8168f6fcba4ab2787d0ff41/raw/29e149f7bb688672cfdad844e308cde4df999e0e/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/b7686518b8168f6fcba4ab2787d0ff41/raw/29e149f7bb688672cfdad844e308cde4df999e0e/jmh-result-candidate.json):
=> [prelude][core] Frame and Log optimizations

kyo-prelude/shared/src/main/scala/kyo/kernel/Context.scala
I've noticed that https://github.com/getkyo/kyo/pull/775 introduced new allocations in the hot path of fiber forking while profiling benchmarks. The `Map.filter` call requires multiple allocations.
This PR creates a fast path that enables `Context.inherit` to execute without allocations in case there are no isolated context effects, which should be the most common scenario. In case isolated effects are present, there's a penalty with additional allocations in both `Context.set` and `Context.inherit`.
I think we'll need to eventually introduce our own collection types. It should be possible to traverse a `Map` to check if there are isolated context keys without allocating, which would avoid the workaround with `IsolationFlag`.
=> [prelude] reduce allocation in Context.inherit

build.sbt, project/Repeat.scala
To make it easier to debug flaky tests. The command stops at the first failure and allows setting a max number of iterations.
=> [build] introduce sbt repeat command

kyo-prelude/shared/src/main/scala/kyo/internal/BaseKyoTest.scala
The execution can get stuck in a `untilTrue` call and never finish. It's not possible to use `Clock` since this code is in `kyo-prelude`.
=> [prelude] add timeout to BaseKyoTest.untilTrue

kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/ClockTest.scala, kyo-data/shared/src/main/scala/kyo/Instant.scala, kyo-data/shared/src/test/scala/kyo/InstantTest.scala
Time-based tests are flaky in JS. It seems the default timer implementation has precision issues. This PR introduces `Clock.nowMonotonic` to provide more a more accurate `Stopwatch` and updates test thresholds to account for the timer imprecision.
=> [core] Clock.nowMonotonic + fix flaky tests in JS

kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
`Async` already handles `Abort[Nothing]` but the effect wasn't included in the type intersection.
=> [core] include Abort[Nothing] in Async

kyo-cache/shared/src/main/scala/kyo/Cache.scala, kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/test/scala/kyo/EnvCombinatorTest.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/ClockTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-prelude/jvm/src/test/scala/kyo/MonadLawsTest.scala, kyo-prelude/shared/src/main/scala/kyo/Parse.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/ParseTest.scala, kyo-prelude/shared/src/test/scala/kyo/VarTest.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/PendingTest.scala
As elaborated in https://github.com/getkyo/kyo/pull/823#discussion_r1833693316, I don't think we need both methods. The `as` name also doesn't feel very intuitive since it doesn't indicate chaining of computations.
=> [prelude][core] Remove `as` from the pending type + make `andThen` always discard

README.md, kyo-bench/src/main/scala/kyo/bench/BlockingContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/CollectParBench.scala, kyo-bench/src/main/scala/kyo/bench/ForkJoinContentionBench.scala, kyo-bench/src/main/scala/kyo/bench/HttpClientContentionBench.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/BarrierTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-core/shared/src/test/scala/kyo/LatchTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala
- Parallel resource closing
- Allows `Abort[Throwable]` in resource close functions
- `Async.parallelGrouped`: similar to `Async.parallel` but with a max parallelism
=> [core] Resource improvements + Async.parallelGrouped

kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala
Hopefully the last bug related to the split of completions and interruptions!
I'm not sure it's possible to provide the exact same behavior in `Fiber.parallel` with bounded parallelism. Since each group runs its computations in sequence via `Kyo.collect`, it can park at any computation even if a following one would fail.
=> [core] fix interrupts in Fiber.parallelUnbounded

kyo-prelude/shared/src/main/scala/kyo/kernel/ArrowEffect.scala
They were used by the `done` function that got removed by https://github.com/getkyo/kyo/pull/828.
=> [prelude] remove unused type parameters in ArrowEffect.handle

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
This PR applies the workaround identified by @hearnadam with an `inline` indirection. I think we should still keep #804 open to explore a more proper solution. Users might need to define methods with boundaries and the workaround can be confusing.
=> [core][combinators] workaround issue with nested boundaries

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
- stop using class member, enforcing accidental eagerness
- add new method: Stream.range to simplify creation of streams
- init/range: accept `chunkSize` to limit size of Chunks- Chunk.from (Array): remove AnyRef type bound
The first PR to address #679. This change is important to ensure the laziness of streams initialized from non-effectful sources.
=> [prelude] make Stream lazier

kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
PR 2 for #679 
Rechunk was a bit tricky to implement as the remaining 'buffer' would get dropped unless the chunks perfectly aligned with the number of emits. Because of this, it's necessary to Emit a final empty chunk to ensure the buffer is flushed. This can sometimes drop the number of elements in a given chunk if a user Emits an empty chunk, but that shouldn't be a problem.
=> [prelude] introduce `Stream#rechunk`

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/regulator/Admission.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/regulator/AdmissionTest.scala
The current mechanism will always penalize the same ids. This PR introduces a time-based window mechanism to rotate which IDs are rejected over time. I've also added a multiplication with a large prime to improve the hash distribution in case the incoming IDs aren't well distributed.
=> [scheduler] Admission rotation window + improve hash distribution

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-data/shared/src/main/scala/kyo/Chunk.scala
New `gather` methods in `Fiber` and `Async` to collect successful computations out of a sequence. It also allows specifying a max number of expected results. See scaladocs for more information.
=> [core] async gather

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-prelude/shared/src/main/scala/kyo/Check.scala, kyo-prelude/shared/src/main/scala/kyo/Emit.scala, kyo-prelude/shared/src/main/scala/kyo/Isolate.scala, kyo-prelude/shared/src/main/scala/kyo/Memo.scala, kyo-prelude/shared/src/main/scala/kyo/Var.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Boundary.scala, kyo-prelude/shared/src/test/scala/kyo/CheckTest.scala, kyo-prelude/shared/src/test/scala/kyo/EmitTest.scala, kyo-prelude/shared/src/test/scala/kyo/IsolateTest.scala, kyo-prelude/shared/src/test/scala/kyo/MemoTest.scala, kyo-prelude/shared/src/test/scala/kyo/VarTest.scala
Please see the `Isolate` scaladoc for more background. Ideally, we should find a way to merge `Boundary` and `Isolate` but that's challenging with the inference issues we've been having and it's difficult to match the current performance of `Boundary` since it's optimized by using more low-level kernel APIs. This new mechanism is focused only on effects that maintain state but don't transform values.
Main benefits of this change:
- It allows users to fork computations with `Var`,  `Emit`, `Memo`, and `Check`. 
- Users can leverage `isolate.run` directly to enforce the effect handling for a computation
- Isolates provide transaction-like behavior via interaction with `Abort`. This behavior will be necessary for an STM-based effect since it'll need to rollback state to retry computations if …
=> [prelude][core] effect isolates

kyo-test/shared/src/main/scala/kyo/test/KyoSpecAbstract.scala, kyo-test/shared/src/test/scala/kyo/test/KyoSpecDefaultSpec.scala
- refactor methods to use `TestConstructor`/`CheckConstructor`
- mark `test`/`suite` as final
- mark `run` as protected
/fixes #877
=> [test] add support for `Gen`/`check`

build.sbt
Moving from https://github.com/getkyo/kyo/pull/878/files#r1864504393 to a separate PR. I'm not sure it was marked as `provided` in the first place but it seems to be necessary so Kyo can be used in Native and JS without having to add the `scala-java-time` dependency explicitly.
=> [build] make scala-java-time a regular dependency

kyo-data/shared/src/main/scala/kyo/Flat.scala
`Flat` was moved to `kyo-data` sometime ago and explicit evidences were introduced. The workaround in the macro isn't necessary anymore.
=> [data] remove Flat check workaround

build.sbt, kyo-bench/src/main/scala/kyo/bench/TMapMultiKeyBench.scala, kyo-bench/src/main/scala/kyo/bench/TMapSingleKeyBench.scala, kyo-bench/src/main/scala/kyo/bench/TRefMultiBench.scala, kyo-bench/src/main/scala/kyo/bench/TRefSingleBench.scala, kyo-core/shared/src/test/scala/kyo/ClockTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/main/scala/kyo/TRefLog.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TRefLogTest.scala
Introduces an initial set of benchmarks for the STM module and optimizes ref log usage. I was surprised by how well optimized ZIO's STM is :)
[Benchmark results](https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/308dc726e9a4f5913170d7d49f7a2dcf/raw/19d284bd0fff6556f83a408db993d4f814b56a89/jmh-result.json):
=> [stm][bench] Ref log optimization + benchmarks

README.md, build.sbt
The compiler can generate a different error message in some cases
=> [readme][build] make unused value warnings a compilation error

kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala, kyo-core/jvm-native/src/main/scala/kyo/KyoAppPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala, kyo-scheduler/js/src/main/scala/java/util/concurrent/ThreadFactory.scala, kyo-scheduler/js/src/main/scala/kyo/scheduler/util/Threads.scala
=> fix: ScalaJS's KyoApp

kyo-core/js-native/src/main/scala/kyo/internal/SignalPlatformSpecific.scala, kyo-core/jvm/src/main/scala/kyo/internal/SignalPlatformSpecific.scala, kyo-core/jvm/src/test/scala/kyo/internal/SignalTest.scala, kyo-core/shared/src/main/scala/kyo/internal/Signal.scala
This is step 1 of solving #491. Next, we need a hook to shutdown the scheduler/interrupt tasks.
=> [core] add `Signal.Handler` class to install shutdown hook

build.sbt, kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-scheduler-cats/jvm/src/main/scala/kyo/KyoSchedulerIOApp.scala, kyo-scheduler-cats/jvm/src/main/scala/kyo/KyoSchedulerIORuntime.scala, kyo-scheduler-cats/jvm/src/test/scala/kyo/KyoSchedulerIOAppTest.scala, kyo-scheduler-cats/jvm/src/test/scala/kyo/KyoSchedulerIORuntimeTest.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/shared/src/main/scala/kyo/scheduler/Task.scala
Benchmark [results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/24a082e8f25d6ca29e02e0720948af3c/raw/c2eb9471cf6a730ee8a636cec9d887733dc6ef0e/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/24a082e8f25d6ca29e02e0720948af3c/raw/c2eb9471cf6a730ee8a636cec9d887733dc6ef0e/jmh-result-candidate.json) are mixed but use in realistic workloads might yield significant improvements, especially in containerized environments given Kyo's adaptive concurrency control.
=> [scheduler] cats-effect integration

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/RetryTest.scala, kyo-data/shared/src/main/scala/kyo/Schedule.scala, kyo-data/shared/src/test/scala/kyo/ScheduleTest.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TSchedule.scala
I'm working on STM optimizations and want to use a jittered schedule to reduce the impact of retry storms. Since we avoid side effects in `kyo-data`, I'm passing the current `Instant` to `schedule.next` and calculating the jitter deterministically via hashing. It isn't random but, given that `Instant` has nanosecond precision, it seems reasonable.
We could pass a random number from `kyo-core` instead but we'd need to eventually pass the instant anyway to implement more advanced schedules like the new `Schedule.anchored` I've also added in this PR.
=> [data] anchored and jittered schedules

kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala
I noticed an odd scenario in a project I'm working on. The `IOPromise` flushing was throwing an exception due to a buggy `onInterrupt` function in the project. This PR ensures exception handling is present in all callback function evaluations.
=> [core] fix IOPromise exception handling

README.md
I did that recently and Metals is more stable!
=> [readme] recommend Metals with SBT BSP

kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/test/scala/kyo/TRefTest.scala
`TRef.initNow` is essentially a footgun. If called within a transaction, it'll make the transaction entry a retry loop for as long as the retry `Schedule` allows. I spent some time debugging an issue caused by this scenario because I added a transaction in an outer scope that had a `Tref.initNow` in it.
=> [stm] use current transaction in initNow if available

kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/PublisherToSubscriberTest.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/reactive-streams/StreamPublisherTest.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/reactive-streams/StreamSubscriberTest.scala
Originally, `Async.sleep` was used to mimic the real-life delay of a publisher/subscriber, but in the `reactive-streams-tck` test cases, it provides little to no benefit while significantly slowing down the overall test. Additionally, a quick look at `fs2` and `zio` shows that they also do not use sleep in their test cases.
This PR takes it a step further by removing `Async.sleep` from all `kyo-reactive-stream` test cases. Since this feature is primarily about correctly combining effects, I believe that if individual components have been thoroughly tested, we can proceed with just the minimal testing.
Furthermore, because `StreamSubscriber` has two strategies, I initially duplicated the tests for both. However, I think it suffices to randomly choose one strategy for each test in the …
=> [kyo-reactive-streams]: Remove un-necessary sleep time in test cases

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/main/scala/kyo/ChunkBuilder.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala
- Extend `StrictOptimizedSeqOps` with `Chunk` to optimize `Seq` based methods
- Improve APIs to correctly return `Chunk[A]` instead of `Seq[A]`
- Optimize `Chunk.Indexed#iterator`
- Optimize `Chunk#take` to avoid allocations
- Optimize `Chunk#appended` to use `Chunk#append`
=> [data] Chunk improvements

kyo-data/shared/src/main/scala/kyo/KyoException.scala
Maybe I'm being superstitious or overly cautious, but I feel like it's much safer if the Exception is initialized with these fields. For interoperability purposes and the like. With the Exception initialized like I'm suggesting, nothing can go wrong ever.
A very small, trivial thing, but I felt a strong urge to do it :sweat_smile:
=> KyoException initialize Exception

README.md, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala
- `Listener#stream` (stream ends when listener is closed)
- `Listener#streamFailing` (aborts with `Closed` when listener is closed)
- `Hub#listen` is now a `Resource` effect, closing listener as finalizer
=> Hub: streaming from Listener

.github/workflows/bench.yml, .github/workflows/build.yml, .github/workflows/readme.yml, .github/workflows/release.yml, .github/workflows/scalafmt.yml
The action caches dependencies across runs: https://github.com/coursier/cache-action
=> [build] use coursier/cache-action

kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm-native/src/test/scala/kyo/scheduler/SchedulerTest.scala, kyo-scheduler/jvm-native/src/test/scala/kyo/scheduler/WorkerTest.scala
There's no need to preempt the current task if the worker queue is empty and there isn't another task waiting for execution.
=> [scheduler] don't preempt task if worker queue is empty

kyo-kernel/shared/src/main/scala/kyo/Kyo.scala
Since `Chunk.size` returns in constant time, there's no need to save the `size` separately. This avoids a field in the captured lambda.
=> [kernel] avoid capturing `size` in Kyo.* methods

kyo-scheduler-cats/jvm/src/main/scala/kyo/KyoSchedulerIORuntime.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/util/Flag.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/util/MovingStdDev.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/util/SelfCheck.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/util/Threads.scala, kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/util/XSRandom.scala
I did some more testing using Kyo's scheduler with cats-effect and identified tunings to offset the regression in some benchmarks. [Results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/396006030e3dae7e157982d04c1f7235/raw/921394ba87a1ffb8f9c09c5a17488c02e23597cf/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/396006030e3dae7e157982d04c1f7235/raw/921394ba87a1ffb8f9c09c5a17488c02e23597cf/jmh-result-candidate.json) with/without the tuning using Kyo's scheduler for both ZIO and cats-effect:
=> [scheduler] tuning + cats improvement + scaladocs

kyo-core/shared/src/main/scala/kyo/Adder.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/test/scala/kyo/AdderTest.scala, kyo-core/shared/src/test/scala/kyo/AtomicTest.scala, kyo-core/shared/src/test/scala/kyo/BarrierTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala, kyo-core/shared/src/test/scala/kyo/LatchTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala
In the majority of the cases, `init` is immediately followed by a `map` to use the new value. This PR introduces a new pattern with `use` methods in the companion objects. It seems a good usability improvement and it'll also help with performance since it avoids a second allocation.
=> [core] introduce `initWith` convenience methods to initialize and use values

kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/util/Singleton.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/SchedulerSingletonTest.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/util/SingletonTest.scala, kyo-scheduler/native/src/main/scala/kyo/scheduler/util/Singleton.scala
I had issues working on similar adaptive schedulers in the past because the scheduler was loaded multiple times due to class loader isolation. The interference between the multiple schedulers can defeat the adaptive behavior. This PR introduces a work around to ensure the scheduler is a singleton even if multiple class loaders are used.
=> [scheduler] ensure the scheduler is a singleton across classloaders

kyo-combinators/shared/src/test/scala/kyo/EmitCombinatorTest.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
Adds methods for performing side effects on streams without altering them.
=> Stream: tap and tapChunk

kyo-kernel/jvm/src/main/scala/kyo/kernel/internal/TracePool.scala, kyo-kernel/jvm/src/test/scala/kyo/kernel/internal/TracePoolConcurrencyTest.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/internal/TracePoolTest.scala
I noticed a [flaky test in CI](https://github.com/getkyo/kyo/actions/runs/12665683690/job/35295758155?pr=984#step:6:5797) and decided to investigate. `TracePool.Local.borrow` returned a `null`, which shouldn't be possible. I wasn't able to reproduce it locally but I've introduced new tests and implemented a preventive measure.
I think there's a possibility that `MpmcArrayQueue.drain` may pass a `null` to the consumer in rare race conditions. I've added a check to ignore values if that's the case. I believe we don't use this method in other places.
=> [kernel] TracePool flaky test

kyo-combinators/shared/src/test/scala/kyo/ResourceCombinatorTest.scala
I noticed this flaky test in CI: https://github.com/getkyo/kyo/actions/runs/12703763768/job/35412083650?pr=959#step:8:2644
=> [combinators] fix flaky test

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
I tried for a couple of hours to avoid `kyoJVM` aggregating `kyo-scheduler-finagle` in Scala 3 but didn't have success. As a work around, I've kept the cross to Scala 3 but disabled all source code + dependency + release in the module's config.
=> [build] fix kyo-scheduler-finagle release

kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Scheduler.scala
We're noticing issues with Scala's standard library assuming all properties contain `String` values:
```
[error] Caused by: java.lang.ClassCastException: class kyo.scheduler.Scheduler cannot be cast to class java.lang.String (kyo.scheduler.Scheduler is in unnamed module of loader sbt.internal.LayeredClassLoader @db22014; java.lang.String is in module java.base of loader 'bootstrap')
[error]         at scala.collection.convert.JavaCollectionWrappers$JPropertiesWrapper$$anon$6.next(JavaCollectionWrappers.scala:614)
[error]         at scala.collection.convert.JavaCollectionWrappers$JPropertiesWrapper$$anon$6.next(JavaCollectionWrappers.scala:609)
[error]         at scala.collection.IterableOnceOps.find(IterableOnce.scala:677)
[error]         at …
```
=> [scheduler] disable singleton mechanism

kyo-data/shared/src/main/scala/kyo/Record.scala, kyo-data/shared/src/main/scala/kyo/internal/FieldsLikeMacro.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala
I haven't found a way to avoid macro (intersection types don't play well with implicits). So I have created typeclass `FieldsLike` (evidence) that splits `Fields` type into tuple of `~` types, and then derives instance for every tuple member.
This typeclass `FieldsLike` could potentially be used for other features like removing fields by keys.
=> [data] records more than 22 AsFields (#1006)

kyo-stm/shared/src/main/scala/kyo/TTable.scala, kyo-stm/shared/src/test/scala/kyo/TTableTest.scala
The wrong implicit was being used to initialize the indexes, which caused all fields to be indexed.
=> [stm] fix TTable index initialization

kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Console.scala, kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Random.scala, kyo-core/shared/src/test/scala/kyo/IOTest.scala, kyo-core/shared/src/test/scala/kyo/RandomTest.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TID.scala, kyo-stm/shared/src/main/scala/kyo/TMap.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala
Getting the value of a `Local` and then immediately performing a side effect is a common pattern in the codebase. See [TRef](https://github.com/getkyo/kyo/blob/9cdf197909d2ecdcd9436f5e9c687f5bbd9b5b2a/kyo-stm/shared/src/main/scala/kyo/TRef.scala#L185) as an example. Other methods like [Clock.deadline](https://github.com/getkyo/kyo/blob/9cdf197909d2ecdcd9436f5e9c687f5bbd9b5b2a/kyo-core/shared/src/main/scala/kyo/Clock.scala#L309) have a similar pattern. 
It currently requires two separate suspensions but that's unnecessary. The local get already suspends execution the same way as `IO` does: via the kernel's internal [Defer](https://github.com/getkyo/kyo/blob/9cdf197909d2ecdcd9436f5e9c687f5bbd9b5b2a/kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Kyo.scala#L80) effect, which is the …
=> [core] introduce IO.withLocal

kyo-prelude/shared/src/test/scala/kyo/ChoiceTest.scala
Kyo provides more strict purity in its implementations due to its support for effects that may invoke the continuation multiple times. Other effect systems typically optimize collection operations by using under-the-hood mutation via builders and iterators but we can't do the same because of the purity restriction. This PR introduces tests to ensure that remains the case or, if we find another solution, multi-shot continuations continue working properly.
=> [prelude] tests for Choice with collection operations

kyo-scheduler/jvm-native/src/main/scala/kyo/scheduler/Scheduler.scala
The mention of default values got out of sync with the recent tuning. I'm removing the default values from the scaladoc to avoid it happening again.
=> [scheduler] fix config scaladocs

kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamPublisher.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscriber.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscription.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/package.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/reactive-streams/package.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/PublisherToSubscriberTest.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/StreamSubscriberTest.scala
/claim #1022
This is an update for post-ack era of `Emit` and `Poll` for `kyo-reactive-stream`
=> Update for kyo-reactive-stream

kyo-data/shared/src/main/scala/kyo/Record.scala, kyo-data/shared/src/main/scala/kyo/Render.scala, kyo-data/shared/src/main/scala/kyo/internal/Inliner.scala, kyo-data/shared/src/main/scala/kyo/internal/TypeIntersection.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala
I had to extend `FieldsLike` evidence to derive `Render` instances, and now it also contains tuples (types) of names and values.
Also I have noticed that an actual type of `~` is never used, so I removed it and now `~` is an abstract type member.
=> [data] add Render instance for Record (#1008)

build.sbt, kyo-scheduler-pekko/jvm/src/main/scala/kyo/scheduler/KyoExecutorServiceConfigurator.scala, kyo-scheduler-pekko/jvm/src/test/scala/kyo/scheduler/KyoExecutorServiceConfiguratorTest.scala
=> [scheduler] pekko integration

kyo-bench/src/main/scala/kyo/bench/CountdownLatchBench.scala, kyo-bench/src/main/scala/kyo/bench/DeepBindBench.scala, kyo-bench/src/main/scala/kyo/bench/EnqueueDequeueBench.scala, kyo-bench/src/main/scala/kyo/bench/ForkChainedBench.scala, kyo-bench/src/main/scala/kyo/bench/PingPongBench.scala, kyo-bench/src/main/scala/kyo/bench/RendezvousBench.scala, kyo-bench/src/main/scala/kyo/bench/SchedulingBench.scala, kyo-bench/src/main/scala/kyo/bench/SemaphoreBench.scala, kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-core/jvm/src/main/scala/kyo/Process.scala, kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala, kyo-kernel/shared/src/main/scala/kyo/Kyo.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscriber.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscription.scala, kyo-stm/shared/src/main/scala/kyo/TTable.scala
This method was introduced before we had the `Kyo` companion object. It doesn't make much sense since I'd expect it to return a suspended computation given the pending `IO`.
=> remove IO.unit

kyo-data/shared/src/main/scala/kyo/internal/BaseKyoDataTest.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala, kyo-data/shared/src/test/scala/kyo/Test.scala, kyo-kernel/shared/src/test/scala/kyo/KyoTest.scala
Closes https://github.com/getkyo/kyo/issues/1033
minimized example why `transparent` helps:
https://scastie.scala-lang.org/road21/1CxBjcGMRdGfeVDg09jjdg
=> make `typeCheck`, `typeCheckFailure` methods transparent

kyo-combinators/shared/src/test/scala/kyo/AbortCombinatorTest.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-core/shared/src/test/scala/kyo/IOTest.scala, kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala, kyo-data/shared/src/main/scala/kyo/internal/BaseKyoDataTest.scala, kyo-data/shared/src/test/scala/kyo/DurationTest.scala, kyo-data/shared/src/test/scala/kyo/InstantTest.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala, kyo-data/shared/src/test/scala/kyo/ResultTest.scala, kyo-data/shared/src/test/scala/kyo/SafeClassTagTest.scala, kyo-data/shared/src/test/scala/kyo/TagTest.scala, kyo-data/shared/src/test/scala/kyo/TypeMapTest.scala, kyo-direct/shared/src/test/scala/kyo/HygieneTest.scala, kyo-kernel/shared/src/test/scala/kyo/KyoTest.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/BoundaryTest.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/LoopTest.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/PendingTest.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/internal/WeakFlatTest.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/EnvTest.scala, kyo-prelude/shared/src/test/scala/kyo/LayerTest.scala, kyo-stm/shared/src/test/scala/kyo/TTableTest.scala
The `assertDoesNotEqual` implementation provided by scalatest doesn't allow matching the error message, which is a source of tech debt as we change the code base. Tests might be continuing passing if we rename methods or types for example
Migrate all tests from `assertDoesNotEqual` to `typeCheckFailure`
=> migrate tests to use typeCheckFailure

kyo-core/jvm/src/main/scala/kyo/StreamCompression.scala, kyo-data/shared/src/main/scala/kyo/KyoException.scala, kyo-data/shared/src/main/scala/kyo/internal/Environment.scala, kyo-data/shared/src/test/scala/kyo/internal/EnvironmentTest.scala
`KyoException` is too verbose in production environments. It's designed to improve the development experience by showing errors with the `Frame` information but, in a production environment, the overhead to log failures can significantly contribute to performance degradation.
Introduce `Environment` that enables the verbose mode only if the user explicitly enables the development mode or sbt entries are present in the classpath, which should be the case for Kyo development environments since we recommend both sbt and metals. The risk of false positives seems low since the check is strict.
I've also improved `KyoException` because I noticed a `NullPointerException`.
=> [data] introduce Environment and improve KyoException

.github/workflows/build-main.yml, .github/workflows/build-pr.yml
We've been having consistent issues with the Scala Native build timing out. I've been debugging this issue for some time and trying several changes but I haven't had success so far. It seems related to concurrency issues in Scala Native's test runner.
Since this is significantly affecting Kyo's development, I think we we could disable the native build for now. I'll dust off an old linux box I have to try to reproduce it locally.
=> [build] disable Scala Native

.github/workflows/build-main.yml, .github/workflows/build-pr.yml
Relates to issue
* https://github.com/getkyo/kyo/pull/1063
Hello @fwbrasil , I see that Scala Native got disabled. It sucks that SN tests were causing issues, but oh well, such is life with bleeding edge tech, like SN.
But if it were only tests which had problems, does that mean that we could still keep SN compilation?
If we keep SN compilation in CI, we could prevent potential incompatibilities from getting merged.
=> Enable Scala Native compilation (tests are still off)

README.md, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala
Fixes #1044 
`Hub`s are initialized with a long-running fiber that should be cleaned up when the hub is no longer being used. This PR makes the initializing methods `init`, `initWith`, and all overloads `Resource` effects, where the finalizer calls `Hub#close`.
`Hub#initWith` uses `Resource.acquireRelease` to construct the `Hub` and calls `_.close.unit` as the finalizer.
=> Hub.init/initWith is Resource

README.md, kyo-aeron/jvm/src/main/scala/kyo/Topic.scala, kyo-bench/src/main/scala/kyo/bench/arena/StreamBench.scala, kyo-bench/src/main/scala/kyo/bench/arena/StreamIOBench.scala, kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamPublisher.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/PublisherToSubscriberTest.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/StreamSubscriberTest.scala
Fixes #1047
Some of the methods in `Stream` have the `run` prefix, which was introduced to indicate that the `stream` will be fully handled and return a computation instead of a `Stream` instance. Renaming the `Stream` methods prefixed with `run` makes it easier to be found
Rename the `Stream` methods
=> rename Stream methods prefixed with run

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-kernel/shared/src/main/scala/kyo/Kyo.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Loop.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Safepoint.scala, kyo-prelude/shared/src/main/scala/kyo/Emit.scala, kyo-prelude/shared/src/main/scala/kyo/Poll.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala
Fixes #1067 
A lot of methods accept effects that are only used for their side-effects and thus typically have a result type of `Unit`. This requires users to frequently append `.unit` to the effects they pass to these methods. This PR changes all such methods to accept effects in the form `Any < S` to remove the need for this boilerplate.
Public discarding methods now accept `Any < S` effects and then convert them to `Unit < S` using `.unit` prior to using them. Generally it is hard to avoid calling `.unit` since these effects are typically passed to methods that require a `Flat` result (`Any` is not guaranteed to be flat.)
Here are the methods that have changed:
- kyo-combinators/Combinators
- `ensuring` 
- kyo-combinators/Constructors
- `Kyo.acquireRelease`
- `Kyo.addFinalizer`
- …
=> 'Discarding' methods accept `Any` instead of `Unit`

.github/workflows/build-pr.yml
PRs trigger a new build on each push, which is typically unnecessary and incurs into costs and overall longer build times sine we have a single dedicated runner.
Limit the concurrency of PR builds so only the latest commit is built and builds for previous commits are automatically cancelled.
=> [build] limit concurrency to only build the last commit of PRs

kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamPublisher.scala, kyo-tapir/shared/src/main/scala/kyo/Routes.scala, kyo-tapir/shared/src/main/scala/kyo/server/NettyKyoServerInterpreter.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/KyoUtil.scala
`.unit` should be avoided where it's possible to discard non-unit values without an additional suspension.
- use `IO(discard(_))` - should we make this a function?
=> Avoid `.unit` where possible

README.md
While I was reading the docs I noticed a few typos so opened this.
=> Fix a few typos in docs

kyo-offheap/native/src/main/java/lang/foreign/MemorySegment.scala, kyo-offheap/shared/src/main/scala/kyo/Memory.scala
The `release` workflow is failing in main since https://github.com/getkyo/kyo/pull/1072 got merged. The compiler for some reason has trouble to generate scaladocs after the `inline` keywords were removed.
I've tried to understand why the compiler was having trouble with scaladocs but the error messages don't show any meaningful information. I've decided to reintroduce inlining to check if the scaladoc generation would work but it actually continues failing but I think the change still makes sense.
=> [offheap] reintroduce inlining

build.sbt, kyo-data/shared/src/main/scala/kyo/Record.scala, kyo-prelude/shared/src/main/scala/kyo/Batch.scala
Fixes problem from https://github.com/scala/scala3/issues/22661#issuecomment-2723119684
Also I have got new compiler warnings that inner (inside `def`) types `cannot be checked at runtime because it's a local class`, so I moved It to internal object.
=> chore: update scala to 3.6.4

kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-core/jvm/src/main/scala/kyo/Process.scala, kyo-core/jvm/src/test/scala/kyo/PathTest.scala
#1084 
> The index parameter is the index of the name element to return. The element that is closest to the root in the directory hierarchy has index 0. The element that is farthest from the root has index [count](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#getNameCount--)-1.
This will only capture files farthest from the root. We may want to produce a tree structure of some kind later.
=> fix: Path#readAll

build.sbt, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
The `release` workflow in main is failing because scaladoc generation of the `kyo-offheapNative` project fails with a compiler crash.
I've tried to fix the issue again without success so, as a workaround, this PR disables scaladoc generation for the module but only for Native. Given that we direct users to the JVM scaladocs, it shouldn't be an issue.
=> [offheap] disable scaladoc generation to fix build

kyo-prelude/shared/src/main/scala/kyo/Env.scala, kyo-prelude/shared/src/main/scala/kyo/Layer.scala, kyo-prelude/shared/src/main/scala/kyo/Local.scala, kyo-prelude/shared/src/test/scala/kyo/EnvTest.scala
The `Env` effect doesn't provide a way to obtain multiple values at once. Also, the scaladocs of `Env` and `Local` don't provide a good mental model for when to use the effects since they're similar
Introduce `Env.getAll` and `Env.useAll` that allows the user to request multiple values via a type intersection, operating at the level of `TypeMap`. Additionally, improve the scaladocs of `Env` and `Local` to provide a better mental model regarding the effects.
- I've renamed `runTypeMap` to `runAll` for consistency
=> [prelude] introduce Env.getAll/useAll + scaladoc improvements

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
The new `Async.zip` methods don't preserve the concurrency of the number of computations being zipped. I think that's not an ideal behavior since the goal of these APIs is to execute computations concurrently.
Ensure the concurrency is preserved by specifying it when calling `collectAll`.
I've also added methods for up to 10 computations.
=> [core] preserve Async.zip concurrency + support up to 10 computations

kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
I'm working on kyo sttp again, and I need an ability to peek the first few element of the stream effectively
I think my proposal `splitAt` can be more generic
=> add `Stream[V, S]`'s `splitAt`

kyo-core/jvm/src/main/scala/kyo/Path.scala
On Windows paths are not correctly splitted, when created from String, because path separator is not correctly escaped. More details in #1106.
`File.separator` has to be correctly used for pattern matching regex, `Pattern.quote(File.separator)`
=> Correct path separator split. Fixes #1106.

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
`Async.foreach(0 until n)(idx => ...)` is a common pattern to repeat a computation with an index.
Add `Async.fillIndexed`.
=> [core] Async.fillIndexed

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/ArrowEffect.scala, kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/main/scala/kyo/Emit.scala, kyo-prelude/shared/src/main/scala/kyo/Env.scala, kyo-prelude/shared/src/main/scala/kyo/Poll.scala, kyo-prelude/shared/src/main/scala/kyo/Var.scala, kyo-tapir/shared/src/main/scala/kyo/Routes.scala
We used to use `Ops` classes to encode methods with multiple type parameter groups. The latest versions of the compiler include the new clause interleaving feature that provides a similar mechanism. I was initially reluctant to adopt it because I thought it could make it harder for people reading the codebase to understand the method signatures but there are important drawbacks with the current `Ops` classes:
- The scaladoc generation isn't great because there's the op builder method indirection
- Use of `pipe` with methods using `Ops` classes require an explicit function. For instance, `a.pipe(Abort.run)` doesn't compile but `a.pipe(Abort.run(_))` does.
- The noise of the `Ops` classes makes the code less readable
Migrate the all `Ops` classes to clause interleaving. To have some …
=> remove Ops classes

README.md, kyo-actor/shared/src/main/scala/kyo/Actor.scala, kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/internal/BaseKyoCoreTest.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala, kyo-core/shared/src/test/scala/kyo/SignalTest.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/PendingTest.scala, kyo-monix/shared/src/main/scala/kyo/Monix.scala, kyo-prelude/shared/src/main/scala/kyo/Parse.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/LayerTest.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala, kyo-prelude/shared/src/test/scala/kyo/debug/DebugTest.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TChunkTest.scala, kyo-stm/shared/src/test/scala/kyo/TMapTest.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala
The `pipe` method is convenient for effect handling but I think using it for arbitrary transformations isn't very intuitive. 
Rename `pipe` to `handle` to more clearly indicate that the method is meant to be used for effect handling. It still supports arbitrary transformations but the scaladocs are also updated to indicate that it's meant primarily for effect handling.
=> [kernel] rename `pipe` to `handle`

kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala
Fixes #739 
With `Abort.fail`, manual type annotations are required to write expressions that fail with literal types.
Add an object `literal` to `Abort` to enable failing with literal types, namely Strings.
The functions will degrade to non-literal behavior in a generic scope.
=> [prelude] Abort with literal types

kyo-scheduler/jvm/src/test/java/examples/JavaSchedulerTest.java
The Scheduler is currently published as a Scala module, so I suspect users may not realize that it's available for other JVM applications.
#1111 
Add an example test in Java to make sure our APIs are always accessible from Java - not depending on Scala specific features.
=> [scheduler] add example of using Scheduler from Java

kyo-data/shared/src/main/scala/kyo/Flat.scala
I noticed the missing scaladoc today and it's an important piece of Kyo's design
=> [data] Flat scaladoc improvement

kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/PublisherToSubscriberTest.scala
Fixes #1122
When a parent `Fiber` is executing and encounters a new child `Fiber` to be waited on, the parent needs to register a callback to propagate interrupts to the child in case there's an interrupt during the waiting. The issue is that, once the child fiber finishes and the parent resumes, the interrupt callback for the child isn't necessary anymore but it stays in the pending list until the parent fully completes execution. This leads to a memory leak when a parent fiber handles many children during its execution.
When the parent fiber resumes execution, remove the interrupt callback for the completed child.
I've also included a fast-path optimization: if the child fiber is already completed, the parent resumes execution immeditely without suspending. There's a performance penalty …
=> [core] fix interrupts leak

kyo-actor/shared/src/main/scala/kyo/Actor.scala, kyo-actor/shared/src/test/scala/kyo/ActorTest.scala
A few improvements in the `kyo-actor` module. Please see comments for more details.
=> [actor] receiveLoop with state + scaladocs + tests

kyo-prelude/shared/src/main/scala/kyo/Var.scala, kyo-prelude/shared/src/test/scala/kyo/VarTest.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala
`Var.andThen` isn't following the pattern of other APIs with the `With` prefix to indicate that the method takes a continuation function.
Update the name.
=> [prelude] rename Var.setAndThen to setWith

build.sbt
Scala Steward isn't working for the repo since Jan.
I don't know if it's related but this PR introduces a config that is suggested in https://github.com/VirtusLab/scala-steward-repos/issues/98#issuecomment-2288919616. I'm not sure what the config supposed to do since I see the regular test logs locally but it seems worth trying.
=> [build] disable test fork output to try fix Scala Steward

kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Loop.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Safepoint.scala, kyo-offheap/shared/src/main/scala/kyo/Memory.scala, kyo-prelude/shared/src/main/scala/kyo/Local.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscriber.scala
Unsealed abstract classes enable for anyone to extend, potentially leading to unsafe/incorrect implementations.
Mark all internal/Unsafe classes as sealed where possible. Note: I think `Meter` should also be sealed, but we had a test abusing the extension - not sure how often people will be creating custom meters.
=> Mark abstract classes as sealed

kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
Creates a stream by repeatedly calling a lazily evaluated function, until the return is absent.
Stream emit an effect until some end state offers no more values.
repeatPresent is a factory method in the Stream class that creates a stream by repeatedly calling a function until it returns an absent value
1. Create a stream from a function that may return values multiple times
2. Automatically terminate the stream when the function returns an absent value
3. Control the chunk size of emitted values for performance optimization
=> Creates a stream by repeatedly calling a lazily evaluated function

kyo-actor/shared/src/test/scala/kyo/ActorTest.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/internal/BaseKyoCoreTest.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/BarrierTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala, kyo-core/shared/src/test/scala/kyo/LatchTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/SignalTest.scala, kyo-kernel/shared/src/main/scala/kyo/internal/BaseKyoKernelTest.scala
Fixes #1138
We have tests disabled in JS because they require multiple threads.
Fix tests to avoid hot loops hogging the JS thread.
=> fix and enable JS tests

kyo-core/shared/src/main/scala/kyo/Resource.scala
`Finalizer` could be implemented a number of ways. Exposing the `Queue` makes the implementation hard to change. Additionally, this makes it more complex when we support hierarchical scopes in #1131.
Use an `abstract class`, exposing only the necessary behaviors. In a followup, I will work towards a rename to `Scope` (optional?), then adding support for `Scope.fork` or some similar naming.
=> Resource: avoid leaking `Queue` based Finalizer details

kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala
`Resources.run` forks a fiber to close resources but it isn't necessary if there are no resources to close.
Complete the promise immediately if the queue is empty.
=> [core] optimize Resource.run without resources

build.sbt
I missed the new version of `dotty-cps-async` in https://github.com/getkyo/kyo/pull/1146 because the project is using a different org id now.
Update the dependency.
=> [build] update dotty-cps-async

kyo-kernel/shared/src/main/scala/kyo/Kyo.scala, kyo-prelude/shared/src/test/scala/kyo/ChoiceTest.scala
Most of `Kyo`'s batch methods are receiving `Seq[A]` only, this PR update them to use `IterableOnce[A]` instead
see https://github.com/getkyo/kyo/issues/1020
=> Update `Kyo`'s batch actions to use IterableOnce

kyo-actor/shared/src/main/scala/kyo/Actor.scala, kyo-combinators/shared/src/main/scala/kyo/AbortCombinators.scala, kyo-combinators/shared/src/main/scala/kyo/KyoCombinators.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/SignalTest.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Loop.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/LoopTest.scala, kyo-prelude/shared/src/main/scala/kyo/Poll.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscriber.scala
I noticed several loops in the codebase written as `Loop(()) { _ =>` which is not very readable. In one of the cases, we need to return a value, which was not possible with `Loop.foreach`
Change `Loop.foreach` to enable returning a value in `done`.
=> [kernel] enable Loop.foreach to return a value

kyo-core/jvm/src/main/scala/kyo/internal/LogPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/test/scala/kyo/LogTest.scala
Fixes #1162 
Users can't pass `Text` into `Log` methods.
Change type signatures to accept `Text`.
=> [core] Log: add support for outputting Text

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-kernel/shared/src/main/scala/kyo/Kyo.scala
We recently introduced the `Single` version of `Chunk`. It's under the `private[kyo]` internal object so it shouldn't leak to users. Also, we'd need to migrate all single-elements calls to `Chunk.apply` to `Chunk.single` to leverage the optimization, which isn't ideal.
Don't expose `Single` in user-facing APIs and override `Chunk.apply` to create `Single` internally in case a single element is passed.
=> [data] introduce optimized override for Chunk.apply

kyo-stm/shared/src/main/scala/kyo/TRef.scala
While debugging https://github.com/getkyo/kyo/issues/1158, I had some trouble to understand the state of `TRefLog` due to the default `toString` of `TRef` being inherited from `AtomicInteger`, which just prints the atomic int value (lock state).
Introduce a custom `toString` showing the state of the `TRef`.
=> [stm] add TRef.toString

kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala
Fixes #1158
When a transaction is rolled back due to an `Abort`, the `STM` effect simply propagates the error. This can be a surprising behavior when the `Abort` happened due to an inconsistent state during the transaction execution, which is an expected scenario given that consistency is checked at commit time. 
In case of errors, check if the ref log is still valid and, if not, wrap the error into `FailedTransaction` to trigger a retry in case the schedule permits.
- I've added `Abort.recoverError` and `Abort.foldError` since it seems a relatively common pattern.
=> [stm] retry Abort when transaction is inconsistent

kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Trace.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/internal/TraceTest.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala
When enriching exceptions, null frames could cause a NPE. See bug #1172 
Check for null frames when initially pushed, as well as when building the saved trace.
There is probably an issue with `IOTask` pushing null traces, but I wasn't able to minimize it quickly. This should be slightly more robust as even if users accidentally push null frames somehow there is protection.
=> fix: NPE when enriching exceptions

kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
This PR introduce some method for `Stream[V, S]`
=> [core] add Stream's `unfoldKyo`

README.md, kyo-combinators/shared/src/main/scala/kyo/AbortCombinators.scala, kyo-combinators/shared/src/main/scala/kyo/ChoiceCombinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-combinators/shared/src/test/scala/kyo/AbortCombinatorsTest.scala, kyo-combinators/shared/src/test/scala/kyo/ChoiceCombinatorsTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala, kyo-direct/shared/src/test/scala/kyo/PreludeTest.scala, kyo-prelude/shared/src/main/scala/kyo/Choice.scala, kyo-prelude/shared/src/main/scala/kyo/Emit.scala, kyo-prelude/shared/src/main/scala/kyo/Parse.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/ChoiceTest.scala, kyo-prelude/shared/src/test/scala/kyo/EmitTest.scala, kyo-prelude/shared/src/test/scala/kyo/debug/DebugTest.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TChunkTest.scala, kyo-stm/shared/src/test/scala/kyo/TMapTest.scala
`Choice.get` follows the API patterns of the early days of the project and only provides a handler to evaluate all alternatives
Rename `Choice.get` to `Choice.eval` and `Choice.eval` to `Choice.evalWith`. Introduce `Choice.runStream`.
I've also added `Emit.valueWhen` used in `runStream`
=> [prelude] Choice.runStream + Emit.valueWhen + refactorings

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/main/scala/kyo/ChunkBuilder.scala, kyo-data/shared/src/test/scala/kyo/ChunkBuilderTest.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala
The overhead of the default Scala collection methods with `Chunk` is the main bottleneck in `StreamBench`.
- Introduce a thread-local cache in `ChunkBuilder` to reuse buffers instead of having to allocate and grow them dynamically, which introduces allocations. 
- Introduce an optimized `foreach` similar to `copyTo` allowing traversal without allocations besides the allocation of the function parameter
- Override other methods like `map` and `filter` to use the optimized `foreach`. To avoid having to allocate the `ChunkBuilder` + the function to call `foreach`, I've introduced `ChunkBuilder.initTransform` that merges the function implementation in the same allocation as `ChunkBuilder`.
=> [data] Chunk optimizations

kyo-data/shared/src/main/scala/kyo/Record.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala
Fix `pendingUntilFixed` test of `Record.stage` after migrating to 3.7.0 (in https://github.com/getkyo/kyo/pull/1175)
Firstly, I have fixed problems with `unlimited recursion` which was similar to (https://github.com/scala/scala3/issues/23137). I have just made scopes of opaque types (`AsFields, AsField`) inside `Record` narrower.
Secondly, I have faced with interesting behavior: moving bound `AsFields` from `unsafeFrom` to `StageOps.apply` changes compiler result. I've spent a lot of time to minimize it to scala compiler bug, but no succeeded.
=> Repair `Record.stage` method after 3.7 migration

kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala
Given:
- A channel.
- A producer that puts items into the channel.
- The produce closes the channel either:
1) when it is empty via `close` or,
2) using `closeAwaitEmpty`.
- A consumer that reads from the channel optimistically using `drain` and,
- if empty, the consumer uses `take` to block until there are new items or the channel is closed.
Then:
- There is a race condition where the consumer is in the middle of draining,
- the channel is not empty,
- the producer closes the channel,
- the consumer returns `Closed` rather than the items drained so far,
- and so items are effectively lost from the end of the channel.
If draining encounters a `Failure[Closed]` and items have been drained, then returns those items.
This is a little tricky to reproduce as it relies on timing. For whatever …
=> Fix channel drain close race

kyo-core/js/src/main/scala/kyo/internal/AsyncPlatformSpecific.scala, kyo-core/js/src/main/scala/kyo/internal/FiberPlatformSpecific.scala, kyo-core/jvm/src/main/scala/kyo/internal/AsyncPlatformSpecific.scala, kyo-core/jvm/src/test/scala/kyo/internal/AsyncPlatformSpecificTest.scala, kyo-core/native/src/main/scala/kyo/internal/AsyncPlatformSpecific.scala, kyo-core/native/src/main/scala/kyo/internal/FiberPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala
`Fiber` is a low-level effect with complex semantics for newcomers. Its functionality is essential for integrations and more low-level code but `Async` provides better usability and covers a majority of use cases. For this reason, `Fiber`'s API has become more limited over time and we don't even provide common combinators like `race` for it since the same functionality can be achieved via `Async` combinators and `Async.run` to obtain a `Fiber`. I hadn't noticed that `fromCompletionStage` is still in `Fiber` and using an old method naming pattern with a `Fiber` suffix.
Move the method to `Async` and remove `fromCompletionStageFiber`.
=> [core] move fromCompletionStage from Fiber to Async

kyo-direct/shared/src/main/scala/kyo/Direct.scala, kyo-direct/shared/src/test/scala/kyo/HygieneTest.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Log.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Pending.scala
#903 
Due to https://github.com/scala/scala3/issues/23018, some defer block are silently transforming from 
```scala
val oups:Int < Abort[String] = Abort.fail("oups")
val x : Unit < Any = {
defer:
oups.now + 1
}
```
to 
```scala
val x: Unit < Any = {
//discard
kernel.`<`.lift(())
}
```
without any warning.
make the compilation fail if we try to lift `Unit < A` into `Unit < B` without `B <:< A`.
=> force compile error of discarded defer block

kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/scheduler/Finalizers.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyo/ResourceTest.scala, kyo-kernel/jvm/src/test/scala/kyo/kernel/internal/SafepointTest.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Safepoint.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/IsolateTest.scala, kyo-prelude/shared/src/main/scala/kyo/debug/Debug.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscriber.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/flow/PublisherToSubscriberTest.scala
When there's a failure, `Resource` is currently not properly waiting for the finalizers to execute before proceeding. Additionally, it doesn't provide a way for finalizers to conditionally execute depending on the outcome of the computation.
Fix the handling in case of failure to ensure the computation waits for finalizers and adapt `Safepoint`, `IO`, and `Resource` to pipe through a `Maybe[Throwable]` to indicate if the computation failed or not so finalizers can implement custom logic.
=> [kernel][core] Resource improvements and fix

kyo-direct/shared/src/test/scala/kyo/CoreTest.scala
Just a cleanup after https://github.com/getkyo/kyo/pull/1204 re-enabling tests cc/ @ahoy-jon
=> [direct] re-enable Queue and Channel tests

kyo-caliban/src/test/scala/kyo/Test.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Timeout.scala, kyo-core/shared/src/main/scala/kyo/internal/BaseKyoCoreTest.scala, kyo-kernel/shared/src/main/scala/kyo/internal/BaseKyoKernelTest.scala, kyo-kernel/shared/src/test/scala/kyo/Test.scala, kyo-prelude/shared/src/test/scala/kyo/Test.scala
This PR aims to solve 2 problems:
1. it's currently impossible to debug test timeouts, as they always point to `Async.timeout(timeout),` in `BaseKyoCoreTest`
2. If you stack timeouts or have any non-trivial indirection, it can be tricky to figure out how long an effect took.
- To solve problem 1, all testing methods needed to propagate a `Frame`. Now the test that is failing is correctly rendered.
- To solve problem 2, I added an argument in the constructor to capture a Duration. It's optional as some timeouts (Deadline) may not have a duration.
A failing test:
```
[info] - ordered runs *** FAILED *** (2 seconds, 13 milliseconds)
[info]   kyo.Fiber$package$Fiber$Interrupted: [2m   │ ──────────────────────────────
[info]    │ // KyoAppTest.scala:39:55 kyo.KyoAppTest._$_$$anon ?
[info]    │ …
```
=> Include Timeout Duration in Timeout Exception

README.md, kyo-combinators/shared/src/main/scala/kyo/AbortCombinators.scala, kyo-combinators/shared/src/main/scala/kyo/ChoiceCombinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-combinators/shared/src/test/scala/kyo/AbortCombinatorsTest.scala, kyo-combinators/shared/src/test/scala/kyo/ChoiceCombinatorsTest.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala, kyo-core/shared/src/test/scala/kyo/HubTest.scala, kyo-core/shared/src/test/scala/kyo/MeterTest.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala, kyo-direct/shared/src/test/scala/kyo/PreludeTest.scala, kyo-direct/shared/src/test/scala/kyo/ShiftTest.scala, kyo-prelude/shared/src/main/scala/kyo/Choice.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/ChoiceTest.scala, kyo-prelude/shared/src/test/scala/kyo/debug/DebugTest.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TChunkTest.scala, kyo-stm/shared/src/test/scala/kyo/TMapTest.scala
`Choice.eval` can be used as a var args. (cf #1216)
---
=> [improvement] var args to Choice.eval (fixes #1216)

kyo-core/shared/src/test/scala/Issue1232.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Safepoint.scala
Fix for #1232, changing the visibility of `Ensure`
---
```
[info] Issue1232:
[info] - IO.ensure *** FAILED *** (321 milliseconds)
[info]   Failure("class Ensure cannot be accessed as a member of (Safepoint$_this :
[info]     ($proxy10 : kyo.kernel.internal.Safepoint.type{type State = Long})) from anonymous class Safepoint$_this.Ensure {...}.
[info]     private[kyo] class Ensure can only be accessed from package kyo.") did not equal <(), the Unit value> (Issue1232.scala:11)
```
---
~I have no idea how to solve that, this doesn't work:~
Solved thanks to @hearnadam 
```diff
* @tparam A
*   The result type of the main computation.
*/
-    inline def ensure[A, S](inline f: => Any < IO)(v: A < S)(using inline frame: Frame): A < (IO & S) =
+    inline def ensure[A, S](inline f: Safepoint ?=> Any …
```
=> [core] fix for #1232

kyo-core/shared/src/main/scala/kyo/Log.scala
Currently `Log` ('safe') converts `Text` prior to invoking the `Unsafe` underlying logger. This is unnecessary as the Unsafe methods accept `Text`.
Pass the values without `show`.
`logWhen` included an unnecessary conversion to `Unit`, so I removed it.
I also converted `Level` to an enum, since the original reason it was converted to a class was simply to add the field `priority`.
=> [core] logging improvements

README.md, kyo-bench/src/main/scala/kyo/bench/ForeachBench.scala, kyo-direct/shared/src/main/scala/kyo/Direct.scala, kyo-direct/shared/src/main/scala/kyo/TestSupport.scala, kyo-direct/shared/src/main/scala/kyo/internal/Validate.scala, kyo-direct/shared/src/test/scala/kyo/CoreTest.scala, kyo-direct/shared/src/test/scala/kyo/HygieneTest.scala, kyo-direct/shared/src/test/scala/kyo/PatMatchTest.scala, kyo-direct/shared/src/test/scala/kyo/PreludeTest.scala, kyo-direct/shared/src/test/scala/kyo/ShiftTest.scala, kyo-direct/shared/src/test/scala/kyo/WhileTest.scala, kyo-examples/jvm/src/main/scala/examples/ledger/api/Endpoints.scala, kyo-examples/jvm/src/main/scala/examples/ledger/api/Handler.scala, kyo-examples/jvm/src/main/scala/examples/ledger/api/Server.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/DB.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Index.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Log.scala
Following a discussion on discord: https://discord.com/channels/1087005439859904574/1245754417840394313/1376094723823108106 
Rename `defer` to `direct`:
```scala
defer:
e.now + 1
```
```scala
direct:
e.now + 1
```
=> [direct] rename defer to direct

README.md, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
Addresses [discussion of resource handling on discord](https://discord.com/channels/1087005439859904574/1087005440623259681/1379902422419509338)
Handling stream effects is currently a little awkward. You have to apply a handler to the stream's `emit` effect and then construct a new Stream from the transformed effect. To handle resources within the scope of a stream, for instance, you would do:
```
val original: Stream[Int, Resource] = ???
val handled: Stream[Int, Any] = Stream(Resource.run(original.emit))
```
This PR adds a `handle` method to `Stream` similar to the `handle` method on `Pending`: it accepts one or more functions transforming the underlying emit effect, and constructs a new stream using the transformed effect. You can handle multiple effects as follows:
```
val original: …
```
=> Stream handle method

.github/workflows/build-pr.yml
The CI can take upwards of 30 minutes sequentially, which is annoying for trying to quickly iterate or solve an issue in non-JVM platform.
Run the CI tasks in separate jobs so they run in parallel.
=> [build] split JVM/JS/Native CI steps to separate Jobs

kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
follow-up of https://github.com/getkyo/kyo/pull/1222
* add `Stream.fromIteratorCatching[E]`
* rewrite `Stream.fromIterator` to use `Stream.fromIteratorCatching`
Note: previous implementation on `fromIterator` was passing the test on `Choice`, because `Stream.repeatPresent` is rechunking. `Choice` over map of impure/effectful construction is still on open subject (not for long).
=> [core] Stream.fromIteratorCatching

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala
`Async.race` completes on the the first success or the last failure. In certain cases, this is undesirable. For example racing a potentially failing computation with a promise that may never complete. The resulting computation will hang indefinitely.
Create a new specialized `Race[E, A]` class extending `IOPromise` in `Fiber`. This will be used to implement customization of Race state without additional overhead of a separate class. This PR adds support for `Success` (existing) and `First` (new).
=> [core] implement `Async.raceFirst`

kyo-core/shared/src/main/scala/kyo/Async.scala
=> Remove redundant reduce

kyo-prelude/shared/src/main/scala/kyo/Poll.scala, kyo-prelude/shared/src/main/scala/kyo/Sink.scala, kyo-prelude/shared/src/test/scala/kyo/PollTest.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscription.scala
While `Poll` does not need variance for `Stream`, now that `Emit[V]` is contravariant with `V`, it makes sense to make `Poll` covariant with `V`. This will allow us to have variance in `Pipe` and `Sink`.
Made `Poll[V]` contravariant with `V` and made all handling methods support partial handling like in `Emit`.
Renamed the `run` overload that runs `Poll` effects against `Emit` effects to `runEmit` since the variance led to type inference issues.
=> Covariant Poll

kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
Fixes #1192 
`mapChunkPar` tests were flaky due to the use of `SignalRef`
Use a channel of size `parallel` instead to limit concurrency.
Also reimplemented `mapPar`, `mapParUnordered`, and `mapChunkParUnordered` similarly without state (they were using `AtomicRef`). I think they are a bit easier to understand this way, and are more consistent with each other now.
=> Reimplement parallel map functions without state

kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
Addresses #679 
There should be an easy way to broadcast streams.
Implemented a variety of `broadcast...` methods. The underlying approach was to make a `StreamHub`, simple wrapper of a `Hub` that communicates elements, failures, and end-of-stream to listeners. `StreamHub` is exposed in the `broadcastDynamic` and `broadcastDynamicWith` methods. Other broadcast methods use it under the hood.
`broadcast2` through `broadcast5` construct tuples of broadcasted streams from the original stream. These guarantee that all streams will consume all elements of the original.
`broadcastN` allows you to specify a number of streams and will construct a chunk of that size (this is based on ZIO's approach)
`broadcasted` generates a stream that subscribes to the hub each time its run so can be reused in …
=> Stream broadcast

build.sbt, kyo-direct/shared/src/main/scala/kyo/internal/AsyncShift.scala, kyo-direct/shared/src/main/scala/kyo/internal/Validate.scala, kyo-direct/shared/src/test/scala/kyo/ShiftTest.scala
thanks to https://github.com/dotty-cps-async/dotty-cps-async/issues/99#issuecomment-2972563568
it's possible to move forward with #1209
----
Maybe:
- - [x] map 
- - [x] flatMap
- - [x] filter
- - [x] exists
- - [x] forall
- - [x] foreach
- - [x] collect
- - [x] getOrElse
Result:
- - [x] map 
- - [x] flatMap
- - [x] filter
- - [x] collect
- - [x] getOrElse
----
For another PR:
Result:
- - [ ] exists
- - [ ] forall
- - [ ] foreach
=> direct on maybe/result

kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
groupedWithin (and other operators) shouldn't close open stream resources.
For now, simply reproduce the issue. I plan to followup with some changes to resource.
=> Add reproducer for 'Stream.groupedWithin' closing resources

kyo-bench/src/main/scala/kyo/bench/ChannelBench.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala
When the producer is faster than a stream consumer (at least in terms of frequency of calls to put and emit, not necessarily overall throughput), the consumer will call take and drain and perform an unnecessary `Chunk.concat`.
Optimistically call `drainUpTo` and only if it is non-empty then call `take`.
Whenever the steam consumer blocks it will always emit a single element before draining the rest. This eliminates all `Chunk.concat` but the chunk sizes will be less consistent. If the consumer cares about this then they should call `rechunk`.
Here are the results of running the benchmark with both the old and new implementations:
```
[info] Benchmark                                      (maxChunkSize)   Mode  Cnt       Score       Error   Units
[info] ChannelBench.streamChunks …
```
=> Channel stream optimistic drain

kyo-data/shared/src/main/scala/kyo/internal/FindEnclosing.scala
Fixes #1286
Synthetic files (scala repl, worksheet, etc) are currently triggering `FindEnclosing.isInternal`
Manually exclude empty files and files starting with `<` - like `<repl>` from internal.
I tested with a publishLocal, but not sure how robust that is. I can't think of a great way to test.
=> Avoid marking synthetic files as internal

kyo-combinators/shared/src/main/scala/kyo/KyoCombinators.scala, kyo-combinators/shared/src/test/scala/kyo/KyoCombinatorsTest.scala
kyo-combinators `ensuring` should accept the same effects as `Resource.ensuring`. It was also missing the variant that propagate the optional error forward.
Update the signature of `kyo-cominator`'s ensuring.
=> [combinator] update `ensuring` to accept `Abort[Throwable]`

README.md, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/test/scala/kyo/QueueTest.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Log.scala
Concludes resource safety API updates (see #1313 for discussion)
`Queue`'s init methods do not guarantee cleanup
Updated init/initWith, added use/initUnscoped/initUnscopedWith both for Queue and Queue.Unbounded variants (left out -With methods for unbounded variants, as these were not included originally)
=> Queue resource safety

kyo-core/shared/src/main/scala/kyo/Stat.scala, kyo-core/shared/src/main/scala/kyo/stats/internal/TraceReceiver.scala, kyo-core/shared/src/main/scala/kyo/stats/internal/TraceSpan.scala, kyo-core/shared/src/test/scala/kyo/stats/internal/TraceReceiverTest.scala, kyo-core/shared/src/test/scala/kyo/stats/internal/TraceSpanTest.scala, kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/main/scala/kyo/Span.scala, kyo-data/shared/src/main/scala/kyo/Tag.scala, kyo-data/shared/src/main/scala/kyo/internal/TagMacro.scala, kyo-data/shared/src/test/scala/kyo/SpanTest.scala, kyo-stats-otel/shared/src/main/scala/kyo/stats/otel/OTelTraceReceiver.scala
`KArray` doesn't follow Kyo's naming patterns.
Rename `KArray` to `Span` (@hearnadam's suggestion). I've also rename the existing tracing `Span` to `TraceSpan` to avoid confusion.
=> [data] rename KArray => Span

kyo-kernel/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/PendingTest.scala
@ahoy-jon found a couple of issues with lifted functions. Due to the definition of the implicit conversions being in the same scope as the definition of `opaque type <`, the compiler doesn't introduce a `lift` conversion, which creates issues with nested computations in generic scopes. Additionally, the compiler is having issues with inlining of pure functions in generic contexts that requires an explicit type annotation.
Introduce the missing `lift` calls in the function conversions and add explicit type annotations in methods that take functions.
=> [kernel] lifted functions fixes

.github/workflows/bench.yml, .github/workflows/build-main.yml, .github/workflows/build-pr.yml, .github/workflows/readme.yml, .github/workflows/release.yml, .github/workflows/scalafmt.yml
The CI was using an old, specific version of JDK21.
Use coursier setup to manage JDK versioning.
I kept bench on JDK21 as I suspect the current async-profiler setup is not correct for JDK24.
=> [build] use setup-action for jdk+sbt setup

kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala, kyo-core/jvm-native/src/main/scala/kyo/KyoAppPlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala
KyoApp is the 'frontend' of users experience Kyo. Let's make it nice!
- Add scaladocs
- rename `timeout` -> `runTimeout` - this is more accurate and prevents imported `timeout` methods from causing compiler errors (like `import Async.timeout`, then `timeout(effect)`
- Introduce `KyoApp.apply` for even simpler running of effects.
=> KyoApp: add ScalaDocs & simplified implementations

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala
/fixes #1339
The current `Async.timeout` avoids forking a fiber to interrupt the computation passed by directlying failing with abort. In the context of a joined Fiber, this means the underlying fiber will never be interrupted.
Avoid the special casing for `Duration.Zero`. Always fork a fiber to interrupt.
=> [core] propagate interruption in Async.timeout when Duration is Zero

kyo-combinators/shared/src/main/scala/kyo/KyoCombinators.scala, kyo-combinators/shared/src/test/scala/kyo/KyoCombinatorsTest.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Loop.scala
- Combinators re-implements some functionality now in prelude. Reuse it where possible.
- `Loop.forever` returns `Unit` instead of `Nothing`
- Fix it 😄
=> [combinators] refine signatures

kyo-direct/shared/src/main/scala/kyo/internal/AsyncShift.scala, kyo-direct/shared/src/main/scala/kyo/internal/Validate.scala, kyo-direct/shared/src/test/scala/kyo/StreamTest.scala
https://github.com/getkyo/kyo/issues/1221 add support for streams
Forms:
```scala
direct:
stream.map(x => f(x).now)
```
* could be valid if unwraped. -> compile error
---
```scala
direct:
stream.map(f)
```
* should be supported without a compile error
---
```scala
direct:
stream.map(x => f(x).later)
```
* should be supported without a compile error
---
```scala
direct:
stream.map(x => direct(f(x).now + 1))
```
* should be supported without a compile error
=> [direct][stream] add stream support in direct

kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-core/jvm-native/src/test/scala/kyo/scheduler/IOPromiseBlockingTest.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Interrupt.scala, kyo-core/shared/src/main/scala/kyo/Interrupted.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/scheduler/IOPromiseTest.scala, kyo-core/shared/src/test/scala/kyo/scheduler/SyncPromiseTest.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamPublisher.scala, kyo-zio/shared/src/main/scala/kyo/ZIOs.scala, kyo-zio/shared/src/test/scala/kyo/ZIOsTest.scala
Merge Interrupt and Interrupted exceptions
Imperative code using Thread interruption will not propagate interruption to the Fiber/Promise being awaited.
Check the Thread interrupt status + restore it.
=> [core] respect Thread interruption on blocking boundaries

README.md, kyo-prelude/shared/src/main/scala/kyo/Layer.scala, kyo-reactive-streams/shared/src/main/scala/kyo/interop/flow/StreamSubscription.scala, kyo-reactive-streams/shared/src/test/scala/kyo/interop/reactive-streams/StreamPublisherTest.scala, kyo-sttp/js/src/main/scala/kyo/PlatformBackend.scala, kyo-sttp/jvm/src/main/scala/kyo/PlatformBackend.scala, kyo-sttp/native/src/main/scala/kyo/PlatformBackend.scala, kyo-sttp/shared/src/main/scala/kyo/Requests.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-sttp/shared/src/test/scala/kyo/RequestsTest.scala
Using Frame.internal reduces the clarity of stack traces.
Remove or limit the scope of Frame.internal where possible.
=> Cleanup usages of `Frame.internal`

kyo-core/shared/src/test/scala/kyo/QueueTest.scala
I ran into some trouble writing tests for #1334 whereby the effects from `Queue.closeAwaitEmpty` were not happening in a deterministic way. The test initially failed in #1261. After updating to the latest changes in main this problem has gone so the fix in there was not needed.
This adds tests to ensure that the behaviour does not regress back again.
=> Add tests for ops allowed after closeAwaitEmpty

kyo-data/shared/src/main/scala/kyo/Text.scala, kyo-data/shared/src/test/scala/kyo/TextTest.scala
Addresses #1382.
`Text#dropUntilNext` was dropping one too many characters.
=> Fix Text#dropUntilNext dropping one too many characters

kyo-data/shared/src/main/scala/kyo/Tag.scala, kyo-data/shared/src/main/scala/kyo/internal/TagMacro.scala, kyo-prelude/shared/src/main/scala/kyo/Aspect.scala
For performance reasons, we don't allow dynamic tags to be inferred within the `kyo` package. This is a good optimization in general but it isn't a strict requirement. For example, in https://github.com/getkyo/kyo/pull/1305 we had to inline methods that don't make sense to inline to work it around, which isn't ideal.
Introduce `Tag.dynamic` to allow bypassing the check within the `kyo` package and use it in `Aspect.init` to avoid the unnecessary inlining in https://github.com/getkyo/kyo/pull/1305. It seems reasonable as an exceptional case.
=> [data][prelude] allow bypassing dynamic tag check + support dynamic tags in Aspect.init

kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala
add a test for
```scala
Abort.catching[E](Abort.panic(new E))
```
I do think we should transform the panic into a failure in this case.
=> test for catching panic
