getkyo/kyo

.github/workflows/benchs.yml
Hopefully it gets rid of the warnings regarding set-state.
=> Update action/cache in CI

docs/index.html
Hi Flavio,
While exploring this cool lib I was switching a lot between my dark mode IDE and the Kyo docs website this was hurting my eyes a bit. 🙈  
To help myself I added a theme and theme-switcher. Perhaps you like it too. 🙃
=> docs: add dark mode

kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/test/scala/kyoTest/fibersTest.scala
This seems a common behavior for effect systems. The current design was based on Twitter's Future, which also doesn't wait for a successful result by default but I think the new behavior is more intuitive given the similarity with ZIO and other similar solutions. Background from discord: https://discord.com/channels/1087005439859904574/1087005440623259681/1222265340319371334
cc/ @jamesward
=> improve Fibers.race to wait for the first successful result

kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala, kyo-core/shared/src/test/scala/kyoTest/Tagged.scala
Resolves https://github.com/getkyo/kyo/issues/204
=> Enable `KyoApp.run` to accept `Aborts[Throwable]`

kyo-core/shared/src/main/scala/kyo/randoms.scala, kyo-core/shared/src/test/scala/kyoTest/randomsTest.scala
I've added a few new methods and restructured the implementation to enable unsafe access for performance-sensitive code.
=> MOAR Randoms (fixes #234)

kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala, kyo-core/shared/src/test/scala/kyoTest/envsTest.scala, kyo-core/shared/src/test/scala/kyoTest/layersTest.scala
=> Replace Evns.Elide and Aborts.Elide with dependant types

kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/package.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala
addresses @hearnadam's [review](https://github.com/getkyo/kyo/pull/248#discussion_r1554304524)
=> improve handling of bugs

kyo-core/shared/src/main/scala/kyo/resources.scala, kyo-core/shared/src/test/scala/kyoTest/resourcesTest.scala
Partially resolves https://github.com/getkyo/kyo/issues/233
Simplified the comment from John to only use `IOs` - we can support other effect types later.
Additionally, we should consider how we can only expose a `Resources.use` function to convert `Resources` to `IOs`... Currently, 'dead' (already closed) Resources can be referenced outside the scope.
=> Enable effectful (IOs) `acquireRelease`

kyo-core/shared/src/main/scala/kyo/streams.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala
Introduces stream chunking based on https://github.com/getkyo/kyo/pull/267. The implementation isn't very sophisticated yet since, for example, it doesn't enforce chunk sizes and any effect in a transformation can hold the processing of the entire chunk. The feature set is enough for my needs in the LLM module for now, though.
I'm actually not sure how to handle effects vs chunking. It seems ZIO's approach breaking chunks can become problematic so we might need to figure out a new and more ergonomic solution.
The performance is closer to the alternatives in the non-buffered benchmark but it's better in the buffered version since Kyo's channels and fibers are much more lightweight:
https://jmh.morethan.io/?source=https://gist.githubusercontent.com/fwbrasil/83f4cd0ccd4d3779561dc774bec2f294/r …
=> streams chunking

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Queue.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala, kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Worker.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/QueueTest.scala, kyo-scheduler/jvm/src/test/scala/kyo/scheduler/WorkerTest.scala
Addresses @He-Pin's [feedback](https://github.com/getkyo/kyo/pull/278#discussion_r1578323355) and improves naming of variables.
=> improve scheduler readability

kyo-core/shared/src/main/scala/kyo/channels.scala, kyo-core/shared/src/main/scala/kyo/chunks.scala, kyo-core/shared/src/main/scala/kyo/hubs.scala, kyo-core/shared/src/main/scala/kyo/ios.scala, kyo-core/shared/src/main/scala/kyo/loops.scala, kyo-core/shared/src/main/scala/kyo/meters.scala, kyo-core/shared/src/main/scala/kyo/queues.scala, kyo-core/shared/src/main/scala/kyo/retries.scala, kyo-core/shared/src/main/scala/kyo/seqs.scala, kyo-core/shared/src/test/scala/kyoTest/loopsTest.scala
I did a review of the codebase to locate loops that can leverage the new `Loops` effect, are missing `@tailrec`, or are stack unsafe.
=> loops review

kyo-core/shared/src/main/scala/kyo/aborts.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala
Followup to https://github.com/getkyo/kyo/pull/292
=> Improve Aborts handling of sub/super types

kyo-bench/src/main/scala/kyo/bench/MtlBench.scala, kyo-core/shared/src/main/scala/kyo/sums.scala, kyo-core/shared/src/test/scala/kyoTest/sumsTest.scala, kyo-tapir/src/main/scala/kyo/routes.scala
Follows the new `Aborts` approach favoring companion object methods.
=> Aborts-like encoding for Sums

README.md, kyo-bench/src/main/scala/kyo/bench/MtlBench.scala, kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/test/scala/kyoTest/abortsTest.scala, kyo-core/shared/src/test/scala/kyoTest/envsTest.scala, kyo-core/shared/src/test/scala/kyoTest/iosTest.scala, kyo-core/shared/src/test/scala/kyoTest/resourcesTest.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/api/Endpoints.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/api/Handler.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/api/Server.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/DB.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/Index.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/Log.scala, kyo-tapir/src/main/scala/kyo/routes.scala
Follows the new Aborts approach favoring companion object methods.
=> Aborts-like encoding for Envs

kyo-bench/src/main/scala/kyo/bench/Bench.scala
It's functional but there's a performance regression. I'm not sure why yet but even benchmarks that don't use the scheduler present new entry for `itable stubs`, which performs interface dispatches, as one of top methods using CPU. Example for a sync benchmark:
A possibility is some call that used to be mono/bimorphic with the default scheduler becomes polymorphic with the scheduler config. I'll follow up on it.
The config is disabled by default and it's necessary to pass the JMH parameter manually when executing benchmarks to activate it.
=> introduce option to replace Zio's executor with Kyo's in benchmarks

README.md, kyo-core/shared/src/main/scala/kyo/defers.scala, kyo-core/shared/src/test/scala/kyoTest/defersTest.scala
Moving some of the changes in https://github.com/getkyo/kyo/pull/308 into separate pull requests. I'll follow up reimplementing both `Locals` and `IOs` in terms of it.
=> introduce Defers effect

kyo-core/shared/src/main/scala/kyo/core.scala, kyo-core/shared/src/main/scala/kyo/ios.scala
I'm working on cleaning up use of core internal classes in effects. This PR introduces a new `eval` method designed to replace a few usage patterns that appear in the `IOs` effect. The method essentially gives the user control over the evaluation of a computation in order to access the `Safepoint` and provide features like exception handling.
=> introduce core eval method

README.md, kyo-bench/src/main/scala/kyo/bench/Bench.scala, kyo-cache/shared/src/main/scala/kyo/caches.scala, kyo-core/js/src/main/scala/kyo/timersSubs.scala, kyo-core/jvm/src/test/scala/kyoTest/MonadLawsTest.scala, kyo-core/shared/src/main/scala/kyo/Duration.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala, kyo-core/shared/src/main/scala/kyo/meters.scala, kyo-core/shared/src/main/scala/kyo/retries.scala, kyo-core/shared/src/main/scala/kyo/timers.scala, kyo-core/shared/src/test/scala/kyoTest/DurationSpec.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala, kyo-core/shared/src/test/scala/kyoTest/KyoTest.scala, kyo-core/shared/src/test/scala/kyoTest/channelsTest.scala, kyo-core/shared/src/test/scala/kyoTest/fibersTest.scala, kyo-core/shared/src/test/scala/kyoTest/metersTest.scala, kyo-core/shared/src/test/scala/kyoTest/retriesTest.scala, kyo-core/shared/src/test/scala/kyoTest/streamsTest.scala, kyo-core/shared/src/test/scala/kyoTest/timersTest.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/api/Server.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/DB.scala, kyo-examples/jvm/src/main/scala/kyo/examples/ledger/db/Log.scala, kyo-tapir/src/main/scala/kyo/server/NettyKyoServer.scala, kyo-test/shared/src/main/scala/kyo/test/KyoSpecDefault.scala, kyo-test/shared/src/test/scala/kyo/test/DurationSpec.scala, kyo-test/shared/src/test/scala/kyo/test/KyoSpecDefaultSpec.scala, kyo-test/shared/src/test/scala/kyo/test/interop/zioSpec.scala
Needs tests + some minor reworking, but should be usable.
Improves compatibility with ZIO interop and general API interop
=> Initial Duration module

kyo-core/js/src/main/scala/kyo/fibersPlatformSpecific.scala, kyo-core/jvm/src/main/scala/kyo/fibersPlatformSpecific.scala, kyo-core/jvm/src/test/scala/kyoTest/completionStageTest.scala, kyo-core/shared/src/main/scala/kyo/fibers.scala
Took a stab at completing https://github.com/getkyo/kyo/issues/323
=> FFI for Java's CompletionStage

kyo-core/shared/src/test/scala/kyoTest/FlatTest.scala, kyo-core/shared/src/test/scala/kyoTest/KyoAppTest.scala
Reproduces #327. I'm pretty sure this used to work, I imagine something broke it along the way and we didn't have a test for it.
=> reproduce flat check bug (#327)

kyo-direct/src/main/scala/kyo/direct.scala
I was attempting to fix [the issue](https://github.com/getkyo/kyo/blob/8553103152e819d16a00c3ff41a6a0bdfb33e7cc/kyo-core/shared/src/main/scala/kyo/aborts.scala#L7) with the direct syntax and opaque types for effects. Although the fix wasn't successful, this PR introduces some refactorings I made during debugging that make the code more readable and reduce the number of transformations between `TypeRepr` and `Type`.
I've identified a workaround to declare opaque effect types, though. I'll prepare another PR with it.
=> direct macro refactorings

kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala
Sttp has an expensive mechanism to [translate exceptions](https://github.com/softwaremill/sttp/blob/v3/core/src/main/scalajvm/sttp/client3/SttpClientExceptionExtensions.scala) to its own types. Since the method is [used as a partial function](https://github.com/softwaremill/sttp/blob/a51c3bb1d047418d1bfd7fe256632b227c15553e/core/src/main/scala/sttp/client3/SttpClientException.scala#L31), each exception handling produces two exceptions: one for `PartialFunction.isDefinedAt` and another for `PartialFunction.apply`. This is quite expensive because the exception types aren't marked as `NoStackTrace` and produce new stack traces on each instantiation. I'll report this issue upstream.
This PR introduces a workaround to avoid translating fiber interruptions specifically since it's the scenario …
=> kyo-sttp: avoid translating Interrupted exceptions

kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/tagsTest.scala
We don't need to support tags for union and intersection types in most scenarios but the ZIO integration needs it in order to integrate environment values between the libraries. This PR introduces support for them but using wrapper APIs so tags still aren't materialized for unions and intersections. The implementation isn't optimized but that should be ok considering the limited use.
=> kyo-tag: support type unions and intersections

README.md, build.sbt
An initial readme entry for the effect.
=> zios: readme

kyo-scheduler-zio/jvm/src/main/scala/kyo/KyoSchedulerZIOAppDefault.scala, kyo-scheduler-zio/jvm/src/test/scala/kyo/KyoSchedulerZIOAppTest.scala
=> add support for KyoSchedulerZIOAppDefault

kyo-core/shared/src/main/scala/kyo/package.scala
I like the bug message! But I thought including a link + cute, tearful emoji might increase the likelihood of receiving issues.
=> Add kyo issues link to bug message

kyo-core/shared/src/main/scala/kyo/envs.scala, kyo-core/shared/src/main/scala/kyo/typeMap.scala, kyo-core/shared/src/test/scala/kyoTest/envsTest.scala, kyo-tapir/shared/src/main/scala/kyo/routes.scala
I'll rebase this atop @hearnadam's changes once they're in.
=> Update `Envs` to use type level map

kyo-caliban/src/test/scala/kyo/resolversTest.scala
I noticed the tests for Caliban that use a server are taking ~12 seconds in my machine. The main wait is when shutting down the server. This PR changes the server config with a shutdown timeout of 5 ms. Each test now takes ~3s in my machine. cc/ @ghostdogpr
=> speedup caliban tests

kyo-core/shared/src/main/scala/kyo/Result.scala, kyo-core/shared/src/test/scala/kyoTest/ResultTest.scala
I'm changing the fiber completion to use `Result[T]` instead of `T < IOs` and noticed that `Result` produces `MatchError`s for successful `null` values. This PR fixes that and also introduces a new convenience `toTry` method.
=> result: support null values

kyo-prelude/shared/src/main/scala/kyo2/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/BoundaryTest.scala
@hearnadam addressing your feedback on https://github.com/getkyo/kyo/pull/489
=> prelude: make boundary constructor private + add convenience apply

kyo-prelude/jvm/src/test/scala/kyo2/MonadLawsTest.scala, kyo-prelude/jvm/src/test/scala/kyo2/kernel/BytecodeTest.scala, kyo-prelude/shared/src/main/scala/kyo2/Abort.scala, kyo-prelude/shared/src/main/scala/kyo2/Maybe.scala, kyo-prelude/shared/src/main/scala/kyo2/Result.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Effect.scala, kyo-prelude/shared/src/test/scala/kyo2/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo2/ChunkTest.scala, kyo-prelude/shared/src/test/scala/kyo2/EnvTest.scala, kyo-prelude/shared/src/test/scala/kyo2/MaybeTest.scala, kyo-prelude/shared/src/test/scala/kyo2/ResultTest.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/EffectTest.scala
I noticed a few issues while porting `kyo-core` to `kyo-prelude`. More background in comments.
=> prelude: Abort/Maybe fixes and improvements

kyo-prelude/shared/src/main/scala/kyo2/kernel/Boundary.scala, kyo-prelude/shared/src/test/scala/kyo2/kernel/BoundaryTest.scala
I'm porting fibers to the new kernel. Methods like `parallel` have to use `Boundary` but calling `Boundary.apply` for each element would introduce overhead. This PR introduces an overloaded `Boundary.apply` that handles a sequence of computations at once.
=> prelude: Boundary for sequences

kyo-prelude/shared/src/main/scala/kyo2/kernel/Frame.scala
I removed the short snippet from the string payload some time ago but forgot to remove its parsing method.
=> remove unused code in Frame

kyo-prelude/jvm/src/test/scala/kyo2/kernel/SafepointTest.scala, kyo-prelude/shared/src/main/scala/kyo2/kernel/Safepoint.scala
I've noticed an bug with `Safepoint.ensure` not executing the ensure thunk when a fiber is interrupted due to the interceptor preempting its execution. This PR fixes this scenario by removing any active interceptors when evaluating the ensure function.
I've also optimized the implementation to reduce allocations.
=> prelude: Safepoint.ensure fix + optimizations

kyo-tag/shared/src/main/scala/kyo/tags.scala, kyo-tag/shared/src/test/scala/kyoTest/tagsTest.scala
=> Fix Tag index out of bounds (#549)

kyo-core/shared/src/main/scala/kyo/typeMap.scala, kyo-core/shared/src/test/scala/kyoTest/typeMapTest.scala
Fixes #545
I would probably expect it to retrieve the last modified first but I couldn't think of an easy way to do this efficiently. First modified first still seems better than a seemingly random order.
=> Typemap deterministic get

kyo-core/js/src/main/scala/kyo/addersStubs.scala, kyo-core/shared/src/main/scala/kyo/adders.scala, kyo-core/shared/src/test/scala/kyoTest/addersTest.scala, kyo-stats-registry/jvm/src/test/scala/kyo/stats/internal/StatsRegistryTest.scala, kyo-stats-registry/shared/src/main/scala/kyo/stats/internal/UnsafeCounter.scala, kyo-stats-registry/shared/src/main/scala/kyo/stats/internal/UnsafeGauge.scala
Closes #410 
/claim #410 
- Handles overflow while calculating the delta in `Counter` and `CounterGauge`
=> fix(stats): Handle delta overflows in Counter and Countergauge 

kyo-prelude/shared/src/main/scala/kyo2/Stream.scala, kyo-prelude/shared/src/test/scala/kyo2/StreamTest.scala
`Stream` currently places pending effects (`S`) as the first generic while `Layer` places it as the last one. I'm also working on a `Join` effect with an `S` parameter and wanted to introduce this convention to make all classes that take `S` place it at the end. I'd be ok with it as the first parameter as well but it'd be important to have a strong convention.
I've also introduced `stream.runForeach` and `Stream.runForeachChunk`.
=> prelude: stream improvements

kyo-prelude/shared/src/main/scala/kyo/kernel/Loop.scala
Given that we have `kyo.Result` now
=> rename Loop.Result to Loop.Outcome

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala
I forgot to move `Chunk` to `kyo-data` in https://github.com/getkyo/kyo/pull/583.
=> move Chunk to kyo-data

README.md
I think we never announced the effect as well.
=> readme: Stream

README.md
Introduces a new readme section for `Layer` cc/ @kitlangton @hearnadam
=> readme: Layer

kyo-data/shared/src/main/scala/kyo/TypeMap.scala, kyo-data/shared/src/test/scala/kyo/TypeMapTest.scala
=> Return Unit for `TypeMap#get[Any]` on empty TypeMap

kyo-scheduler/jvm/src/main/scala/kyo/scheduler/Scheduler.scala
I'm doing some testing where a large number of workers are created and the mechanism that periodically cycles workers introduces significant overhead.
=> scheduler: optimize worker cycling

kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala
Addressing a TODO. I couldn't see a significant change in benchmark results, though.
=> kernel: inline <.unit

README.md, kyo-core/jvm/src/main/scala/kyo/Path.scala, kyo-core/jvm/src/main/scala/kyo/Process.scala, kyo-core/jvm/src/test/scala/kyo/ProcessTest.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/RetryTest.scala, kyo-core/shared/src/test/scala/kyo/SystemTest.scala, kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/main/scala/kyo/Duration.scala, kyo-data/shared/src/main/scala/kyo/Result.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala, kyo-data/shared/src/test/scala/kyo/DurationSpec.scala, kyo-data/shared/src/test/scala/kyo/ResultTest.scala, kyo-examples/jvm/src/main/scala/examples/ledger/api/Server.scala, kyo-examples/jvm/src/main/scala/examples/ledger/db/Index.scala, kyo-prelude/jvm/src/test/scala/kyo/MonadLawsTest.scala, kyo-prelude/shared/src/main/scala/kyo/Abort.scala, kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala, kyo-prelude/shared/src/test/scala/kyo/LayerTest.scala, kyo-tapir/shared/src/main/scala/kyo/server/NettyKyoServer.scala
=> core: introduce System

README.md, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/test/scala/kyo/BarrierTest.scala
In honor of the 500th person to star the repository 🎉 Thank you @wendersonferreira!!
=> core: Barrier

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, kyo-data/shared/src/test/scala/kyo/DurationSpec.scala, kyo-prelude/jvm/src/main/scala/kyo/kernel/Platform.scala, kyo-prelude/jvm/src/main/scala/kyo/kernel/TracePool.scala, kyo-prelude/native/src/main/scala/kyo/kernel/Platform.scala, kyo-prelude/native/src/main/scala/kyo/kernel/TracePool.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-prelude/shared/src/test/scala/kyo/ChoiceTest.scala, kyo-prelude/shared/src/test/scala/kyo/KyoTest.scala, kyo-prelude/shared/src/test/scala/kyo/Tagged.scala, project/plugins.sbt
I was surprised by how easy it was to add Scala Native support!
=> Scala Native support for kyo-tag, kyo-data, kyo-prelude

kyo-combinators/shared/src/main/scala/kyo/Combinators.scala, kyo-combinators/shared/src/main/scala/kyo/Constructors.scala, kyo-combinators/shared/src/test/scala/kyo/AbortCombinatorTest.scala, kyo-combinators/shared/src/test/scala/kyo/ConstructorsTest.scala, kyo-combinators/shared/src/test/scala/kyo/EffectCombinatorTest.scala, kyo-combinators/shared/src/test/scala/kyo/FiberCombinatorTest.scala
I noticed a couple of bugs and missing test coverage while adding the scaladocs.
=> combinators: scaladocs, fixes, and tests

README.md, build.sbt, kyo-cats/shared/src/main/scala/kyo/Cats.scala, kyo-cats/shared/src/test/scala/kyo/CatsTest.scala, kyo-cats/shared/src/test/scala/kyo/Test.scala
I wanted to avoid this integration because of past issues with Typelevel, but I think it's best if we get ahead of a possible integration and ensure it's under our control in the repository.
=> cats-effect integration

kyo-core/shared/src/main/scala/kyo/Access.scala, kyo-core/shared/src/main/scala/kyo/Adder.scala, kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Console.scala, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Log.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/Random.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-core/shared/src/main/scala/kyo/Stat.scala, kyo-core/shared/src/main/scala/kyo/System.scala, kyo-core/shared/src/main/scala/kyo/Timer.scala
Clock is covered by https://github.com/getkyo/kyo/pull/637
=> core: scaladocs

kyo-bench/src/main/scala/kyo/bench/Registry.scala, kyo-core/jvm/src/main/scala/kyo/Path.scala
fixes #657
I'm not sure it's worth making it testable.
=> core: fix file path separators

README.md, kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala, kyo-prelude/shared/src/main/scala/kyo/Batch.scala, kyo-prelude/shared/src/main/scala/kyo/Choice.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/BatchTest.scala
An effect that provides functionality similar to ZIO Query.
=> prelude: Batch effect

kyo-prelude/shared/src/main/scala/kyo/internal/LayerMacros.scala
=> prelude: use Ansi in LayerMacros

kyo-core/shared/src/main/scala/kyo/Async.scala, kyo-core/shared/src/main/scala/kyo/scheduler/Ensures.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala
The regressions seem to be just noise.
https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/1449324e996db52fc3632d0b5d115933/raw/f02a69655e1ca4f3fcd710cced12e982a619f09f/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/1449324e996db52fc3632d0b5d115933/raw/f02a69655e1ca4f3fcd710cced12e982a619f09f/jmh-result-candidate.json
=> core: async optimizations

kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
=> Fix Stream.runDiscard not processing any stream elements

kyo-prelude/shared/src/main/scala/kyo/kernel/Frame.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/FrameTest.scala
=> Omit snippet for internal Frames

kyo-prelude/shared/src/main/scala/kyo/Emit.scala, kyo-prelude/shared/src/main/scala/kyo/Stream.scala, kyo-prelude/shared/src/test/scala/kyo/EmitTest.scala, kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
=> prelude: change Emit.Ack.Stop to be 0 (#696)

kyo-core/shared/src/test/scala/kyo/AsyncTest.scala, kyo-core/shared/src/test/scala/kyo/FiberTest.scala
leftover from https://github.com/getkyo/kyo/pull/727
=> core: extract FiberTest from AsyncTest

kyo-data/shared/src/main/scala/kyo/SafeClassTag.scala, kyo-data/shared/src/main/scala/kyo/internal/SafeClassTagMacro.scala, kyo-data/shared/src/test/scala/kyo/SafeClassTagTest.scala
first step for https://github.com/getkyo/kyo/issues/739
=> data: support literal types in SafeClassTag

kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-data/shared/src/main/scala/kyo/Instant.scala, kyo-data/shared/src/test/scala/kyo/InstantTest.scala
Added missing `infix` modifiers + `<`, `<=`, `>`, `>=`, `between`, `clamp`
=> data: Instant improvements

kyo-core/shared/src/main/scala/kyo/Random.scala, kyo-core/shared/src/test/scala/kyo/RandomTest.scala
Following up on https://github.com/getkyo/kyo/pull/780#discussion_r1818130462
=> [core] more convenient Random customization

README.md, kyo-core/shared/src/main/scala/kyo/KyoApp.scala, kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala, kyo-test/shared/src/main/scala/kyo/test/KyoSpecDefault.scala
=> core: simplify KyoApp

kyo-prelude/shared/src/main/scala/kyo/Batch.scala
The compiler started warning since the last update. The code is correct so I'm suppressing the warning
```
[warn] -- [E029] Pattern Match Exhaustivity Warning: /Users/fwbrasil/workspace/kyo/kyo-prelude/shared/src/main/scala/kyo/Batch.scala:153:16
[warn] 153 |                case (_: Unit, items) =>
[warn]     |                ^
[warn]     |   match may not be exhaustive.
[warn]     |
[warn]     |   It would fail on pattern case: (_: internal.Source[Any, Any, S], _)
[warn]     |
[warn]     | longer explanation available when compiling with `-explain`
```
=> [prelude] fix Batch compilation warning

README.md, build.sbt
Also updates the `README` recommending the same to users.
=> [build] make discarded computations compilation failures

kyo-data/shared/src/main/scala/kyo/Text.scala, kyo-data/shared/src/test/scala/kyo/TextTest.scala
This PR adds a `Predicate` abstract class to avoid boxing on each character read since Scala 3 still doesn't specialize functions + scaladocs + a few new methods
=> [data] Text improvements

kyo-core/shared/src/test/scala/kyo/FiberTest.scala
I noticed the tests failing in CI
=> [core] fix flaky fiber tests

kyo-prelude/jvm/src/test/scala/kyo/kernel/BytecodeTest.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/ArrowEffect.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Boundary.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Context.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/ContextEffect.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Effect.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Loop.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Reducible.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Safepoint.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/Trace.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/WeakFlat.scala, kyo-prelude/shared/src/main/scala/kyo/kernel/package.scala, kyo-prelude/shared/src/test/scala/kyo/kernel/ArrowEffectTest.scala
Most of the changes are scaladocs but I also reduced the visibility of additional APIs and removed a few unnecessary parameters.
=> [prelude] kernel scaladocs + cleanups

build.sbt, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala
Fixes #898
I saw flaky JVM tests in CI and decided to look into it. The test failures in Native were actually due to a race condition during commit.
=> [stm] fix race condition during commit + enable Native

kyo-stm/shared/src/main/scala/kyo/TChunk.scala, kyo-stm/shared/src/main/scala/kyo/TSchedule.scala, kyo-stm/shared/src/test/scala/kyo/TChunkTest.scala, kyo-stm/shared/src/test/scala/kyo/TScheduleTest.scala
Transactional versions for a couple of `kyo-data` APIs
=> [stm] TChunk and TSchedule

README.md, kyo-bench/src/main/scala/kyo/bench/RendezvousBench.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Fiber.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/test/scala/kyo/AtomicTest.scala
=> [core] rename atomic cas to compareAndSet

kyo-bench/src/main/scala/kyo/bench/TRefMultiBench.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-prelude/shared/src/main/scala/kyo/Local.scala, kyo-prelude/shared/src/main/scala/kyo/Var.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TID.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/main/scala/kyo/TRefLog.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TRefLogTest.scala
Benchmark [results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/fwbrasil/28a2f0957f839310a85752634904a99d/raw/e414912bcd3b7d89d43663298a40a5e3dd5c560d/jmh-result-baseline.json,https://gist.githubusercontent.com/fwbrasil/28a2f0957f839310a85752634904a99d/raw/e414912bcd3b7d89d43663298a40a5e3dd5c560d/jmh-result-candidate.json):
=> [stm] optimizations

kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Context.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Kyo.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/internal/Trace.scala
Scaladocs for some internal types to make it easier to follow the code.
=> [kernel] additional scaladocs

kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/test/scala/kyo/ChannelTest.scala
Added `Channel#putBatch` method that adds a chunk of elements to a channel in a batch. It will break up the chunk into multiple batches if the chunk exceeds the channel capacity.
=> Channel: batched put

kyo-core/js/src/main/scala/kyo/scheduler/IOPromisePlatformSpecific.scala, kyo-core/jvm/src/main/scala/kyo/scheduler/IOPromisePlatformSpecific.scala, kyo-core/native/src/main/scala/kyo/scheduler/IOPromisePlatformSpecific.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala
Fixes https://github.com/getkyo/kyo/issues/874
=> [core] avoid AtomicReference allocation in IOPromise

kyo-core/shared/src/main/scala/kyo/IO.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOPromise.scala, kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/Effect.scala
I noticed a few regressions with recent changes while inspecting benchmarks
=> [kernel][core] IO and Async optimizations

kyo-bench/src/main/scala/kyo/bench/TMapMultiKeyBench.scala, kyo-bench/src/main/scala/kyo/bench/TMapSingleKeyBench.scala, kyo-bench/src/main/scala/kyo/bench/TRefMultiBench.scala, kyo-bench/src/main/scala/kyo/bench/TRefSingleBench.scala, kyo-stm/shared/src/main/scala/kyo/STM.scala, kyo-stm/shared/src/main/scala/kyo/TChunk.scala, kyo-stm/shared/src/main/scala/kyo/TMap.scala, kyo-stm/shared/src/main/scala/kyo/TRef.scala, kyo-stm/shared/src/main/scala/kyo/TSchedule.scala, kyo-stm/shared/src/test/scala/kyo/STMTest.scala, kyo-stm/shared/src/test/scala/kyo/TChunkTest.scala, kyo-stm/shared/src/test/scala/kyo/TRefTest.scala, kyo-stm/shared/src/test/scala/kyo/TScheduleTest.scala
Following up on https://github.com/getkyo/kyo/pull/959#discussion_r1898750872 and https://github.com/getkyo/kyo/pull/984
=> [stm] remove initNow and introduce initWith

kyo-core/jvm/src/main/scala/kyo/StreamCompression.scala, kyo-core/jvm/src/test/scala/kyo/StreamCompressionTest.scala, kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-prelude/shared/src/main/scala/kyo/Abort.scala
The second step toward solving #764, this ticket introduce `Deflate`/`Inflate` and `Gzip`/`Gunzip` to Kyo's `Stream[Byte, S]`.
=> Kyo's stream compressions

build.sbt, kyo-offheap/jvm/src/main/scala/kyo/Memory.scala, kyo-offheap/jvm/src/test/scala/kyo/MemoryTest.scala, kyo-offheap/jvm/src/test/scala/kyo/Test.scala
I've put it in a new module because I have plans to introduce new off-heap data structures.
=> [offheap] introduce module

kyo-cache/shared/src/main/scala/kyo/Cache.scala, kyo-core/shared/src/main/scala/kyo/Hub.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-sttp/jvm/src/main/scala/sttp/client3/HttpClientKyoBackend.scala, kyo-sttp/shared/src/main/scala/kyo/internal/KyoSttpMonad.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/KyoUtil.scala, kyo-tapir/shared/src/main/scala/kyo/server/internal/NettyKyoRequestBody.scala
A cleanup and minor optimization
=> use initWith where possible

kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-data/shared/src/test/scala/kyo/AnsiTest.scala
=> test incremental PR

kyo-data/shared/src/main/scala/kyo/Record.scala, kyo-data/shared/src/test/scala/kyo/RecordTest.scala
Closes https://github.com/getkyo/kyo/issues/1051
=> fix: bug CanEqual derivation for records

README.md
@julien-truffaut I took your changes a bit further and tried to clarify your questions
=> readme: fix typos, outdated snippets, and language

kyo-core/shared/src/main/scala/kyo/Fiber.scala
I noticed a few builds failing after https://github.com/getkyo/kyo/pull/1086. This error should only happen if a `Safepoint` from one thread leaks to the execution in another thread via implicits, introducing concurrency issues since the `Trace` management is meant to used by its owning thread only and isn't synchronized:
```
[info] - no buffer *** FAILED *** (6 milliseconds)
[info]   java.lang.NullPointerException: Cannot invoke "kyo.kernel.internal.Trace.frames()" because "newTrace" is null
[info]   at kyo.kernel.internal.Trace$Owner.copyTrace(Trace.scala:60)
[info]   at kyo.Fiber$package$Fiber$$anon$33$$anon$34.loop$8(Fiber.scala:497)
[info]   at kyo.Fiber$package$Fiber$$anon$33$$anon$34.apply(Fiber.scala:661)
[info]   at kyo.Fiber$package$Fiber$$anon$33$$anon$34.apply(Fiber.scala:495) …
```
=> [core] fix safepoint leak in Fiber

kyo-kernel/shared/src/main/scala/kyo/kernel/Pending.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/PendingTest.scala
I've been using `pipe` more and I've reached a case where I wanted to have more than 6 transformations.
Introduce transformations for up to 10 transformations.
=> [kernel] pipe with up to 10 transformations

CONTRIBUTING.md
The repository doesn't have a `CONTRIBUTIING.md` file. This PR is meant to add one.
Addition of a `CONTRIBUTING.md` file.
PR to close #1068
=> Add CONTRIBUTINGmd

kyo-core/shared/src/main/scala/kyo/Access.scala, kyo-core/shared/src/main/scala/kyo/Adder.scala, kyo-core/shared/src/main/scala/kyo/Atomic.scala, kyo-core/shared/src/main/scala/kyo/Barrier.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/Clock.scala, kyo-core/shared/src/main/scala/kyo/Latch.scala, kyo-core/shared/src/main/scala/kyo/Meter.scala, kyo-core/shared/src/main/scala/kyo/Queue.scala, kyo-core/shared/src/main/scala/kyo/Random.scala, kyo-core/shared/src/main/scala/kyo/Resource.scala, kyo-core/shared/src/main/scala/kyo/Retry.scala, kyo-core/shared/src/main/scala/kyo/System.scala
=> [core] improve scaladocs

kyo-prelude/shared/src/test/scala/kyo/StreamTest.scala
Stream operators in ZIO are notorious for breaking chunking - which is often unexpected.
Add a suite of tests to validate Chunking behaviors for both Kyo and pure version of stream operators.
=> [prelude] add chunking related tests

build.sbt, kyo-bench/src/main/scala/kyo/bench/arena/HttpClientBench.scala, kyo-bench/src/main/scala/kyo/bench/arena/HttpClientContentionBench.scala, project/plugins.sbt
Scala Steward is still not working for the repo.
Update dependencies manually.
=> [build] update dependencies

kyo-data/shared/src/main/scala/kyo/Chunk.scala
Add `Chunk.Single`
More information at #1128
=> [Feature] Add Chunk.Single

kyo-core/jvm/src/test/scala/kyo/PathTest.scala, kyo-core/shared/src/main/scala/kyo/Channel.scala, kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
Address #679 
We need to be able to transform stream elements and chunks asynchronously
Added the following methods to `Stream`:
- `mapPar`
- `mapParUnordered`
- `mapChunkPar`
- `mapChunkParUnordered`
=> Parallel stream map

kyo-data/shared/src/main/scala/kyo/Tag.scala, kyo-data/shared/src/main/scala/kyo/TypeMap.scala, kyo-data/shared/src/main/scala/kyo/internal/TagMacro.scala, kyo-data/shared/src/test/scala/kyo/TagTest.scala, kyo-kernel/shared/src/main/scala/kyo/kernel/ArrowEffect.scala, kyo-kernel/shared/src/test/scala/kyo/kernel/ArrowEffectTest.scala, kyo-offheap/shared/src/main/scala/kyo/Memory.scala, kyo-stm/shared/src/main/scala/kyo/TRefLog.scala
Please see comments for details.
=> [data][kernel] Tag improvements + use <:< in ArrowEffect

kyo-core/shared/src/main/scala/kyo/scheduler/IOTask.scala
When a fiber encounters a child fiber/promise to wait on during execution, `IOTask` currently resumes the parent in a new `IOTask` instance after the child completes. Besides the performance cost, this makes the identity of a fiber not stable since it might be executing in a linked `IOTask` instance if it got suspended by a child fiber. It's a blocker to implement fiber trace dumps for example since the actual execution trace might in a linked `IOTask` instance.
Adapt the logic to simply resume the `IOTask` after a child completes and the execution of the parent needs to resume.
=> [core] stable fiber identity

kyo-core/shared/src/main/scala/kyo/Channel.scala
We're still getting build [failures](https://github.com/getkyo/kyo/actions/runs/15153342865/job/42603387092#step:6:6692) and I noticed the exception is reporting the wrong `Frame`. The initial frame is kept to report where the closed resource was created but the actual frame of the exception should come from the current operation being executed.
Properly propagate the `Frame`. This might help identify the issue since I'm not able to reproduce it locally cc/ @steinybot
=> [core] fix Channel closed exception frame

README.md
=> Add a link to the TechEmpower's benchmark example

README.md
Don't know if the README.md should be updated with something not released yet.
=> update readme.md for kyo-direct

kyo-kernel/shared/src/test/scala/kyo/KyoTest.scala
=> [kernel] add tests in KyoTest.scala

kyo-data/shared/src/main/scala/kyo/Chunk.scala, kyo-data/shared/src/test/scala/kyo/ChunkTest.scala
Get the last element from a `Chunk`.
Add a `lastMaybe` method which is analgous to `headMaybe`.
=> Add Chunk lastMaybe

kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala, kyo-core/shared/src/test/scala/kyo/StreamCoreExtensionsTest.scala
Implement `Stream.fromIterator`
---
=> [feature] Stream.fromIterator

CONTRIBUTING.md
Could be called "things I wish I would have known before contributing to `Kyo`".
I will go back to my last PRs, and try to sum it up here.
@johnhungerford @fwbrasil @hearnadam don't hesitate to use directly PR suggestions on this one.
---
=> update Contributing to add some design guidelines

kyo-kernel/shared/src/test/scala/kyo/KyoTest.scala
=> fix #1301: issue with expected toString Rep in test

README.md, build.sbt
following : https://github.com/getkyo/kyo/pull/1344
=> add mdoc:skip for invalid scala code

README.md
I noticed a few issues while adding slides.
=> README: add slides + fixes

kyo-data/shared/src/main/scala/kyo/internal/BaseKyoDataTest.scala, kyo-data/shared/src/main/scala/kyo/internal/TagMacro.scala, kyo-data/shared/src/test/scala/kyo/TagTest.scala
Bug #1368
For now, just reproduce the issue.
=> [data] reproduce TagMacro issue with opaque types + variance

README.md, docs/index.html
=> Added Copy To Code Functionality
